function k(b,a,c,d,e){b.u.Db(b.fb,a,c,d,e)}function l(b,a,c,d){b.u.da?k(b,a,c,d):b.u.Ae()._OnMessageFromDOM({type:"event",component:b.fb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.u.D(b.fb,a,c)}function r(b,a){for(const [c,d]of a)n(b,c,d)}function u(b){b.Nb||(b.u.te(b.Rd),b.Nb=!0)}window.Bb=class{constructor(b,a){this.u=b;this.fb=a;this.Nb=!1;this.Rd=()=>this.xa()}Wc(){}xa(){}};function aa(b){-1!==b.Ua&&(self.clearTimeout(b.Ua),b.Ua=-1)}
window.pe=class{constructor(b){this.Dc=b;this.Re=5;this.Ua=-1;this.Pb=-Infinity;this.Sd=()=>{this.Ua=-1;this.Pb=Date.now();this.kb=!0;this.Dc();this.kb=!1};this.ud=this.kb=!1}j(){aa(this);this.Sd=this.Dc=null}};"use strict";function ba(b,a){const c=a.elementId,d=b.$c(c);b.W.set(c,d);d.style.boxSizing="border-box";a.isVisible||(d.style.display="none");d.addEventListener("focus",()=>{v(b,"elem-focused",c)});d.addEventListener("blur",()=>{v(b,"elem-blurred",c)});b.cb&&document.body.appendChild(d)}
function w(b,a,c){n(b,a,d=>{const e=b.W.get(d.elementId);return c(e,d)})}function v(b,a,c,d){d||(d={});d.elementId=c;k(b,a,d)}
window.je=class extends self.Bb{constructor(b){super(b,"user-media");this.W=new Map;this.cb=!0;r(this,[["create",a=>ba(this,a)],["destroy",a=>{a=a.elementId;const c=this.W.get(a);this.bd(c);this.cb&&c.parentElement.removeChild(c);this.W.delete(a)}],["set-visible",a=>{this.cb&&(this.W.get(a.elementId).style.display=a.isVisible?"":"none")}],["update-position",a=>{if(this.cb){var c=this.W.get(a.elementId);c.style.left=a.left+"px";c.style.top=a.top+"px";c.style.width=a.width+"px";c.style.height=a.height+
"px";a=a.fontSize;null!==a&&(c.style.fontSize=a+"em")}}],["update-state",a=>{this.W.get(a.elementId);this.gd()}],["focus",a=>{const c=this.W.get(a.elementId);a.focus?c.focus():c.blur()}],["set-css-style",a=>{this.W.get(a.elementId).style[a.prop]=a.val}],["set-attribute",a=>{this.W.get(a.elementId).setAttribute(a.name,a.val)}],["remove-attribute",a=>{this.W.get(a.elementId).removeAttribute(a.name)}]]);w(this,"get-element",a=>a)}$c(){throw Error("required override");}bd(){}gd(){throw Error("required override");
}};"use strict";const ca=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),x=/android/i.test(navigator.userAgent);let da=0;function z(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.cf?new Promise(c=>{const d="c3_resolve_"+da;++da;self[d]=c;a.textContent=b.gf+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let ea=!1,fa=!1;
function ha(){if(!ea){try{new Worker("blob://",{get type(){fa=!0}})}catch(b){}ea=!0}return fa}let A=new Audio;const ia={"audio/webm; codecs=opus":!!A.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!A.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!A.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!A.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!A.canPlayType("audio/mp4"),"audio/mpeg":!!A.canPlayType("audio/mpeg")};A=null;
async function ja(b){b=await ka(b);return(new TextDecoder("utf-8")).decode(b)}function ka(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const B=[];let C=0;window.RealFile=window.File;const E=[],F=new Map,G=new Map;let la=0;const ma=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");ma.push(b)};const na=new Set(["cordova","playable-ad","instant-games"]);
let oa=!1;
window.ab=class b{constructor(a){this.da=a.jf;this.ta=null;this.ba="";this.dc=a.ff;this.yb={};this.Na=this.xb=null;this.Lb=[];this.G=this.Sa=null;this.Lc=!1;this.xd=0;this.mb=null;this.Ra=-1;this.Xe=()=>this.Ie();this.Qa=[];this.C=a.Td;this.Ob="file"===location.protocol.substr(0,4);!this.da||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ha()||(this.da=!1);if("playable-ad"===this.C||"instant-games"===this.C)this.da=!1;if("cordova"===this.C&&this.da)if(x){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.da=!1)}else this.da=!1;this.Sb=this.ma=null;"html5"!==this.C||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.D("runtime","cordova-fetch-local-file",c=>this.Ee(c));this.D("runtime","create-job-worker",()=>this.Fe());"cordova"===this.C?document.addEventListener("deviceready",()=>this.ld(a)):this.ld(a)}j(){this.tc();
this.ta&&(this.ta=this.ta.onmessage=null);this.xb&&(this.xb.terminate(),this.xb=null);this.Na&&(this.Na.j(),this.Na=null);this.G&&(this.G.parentElement.removeChild(this.G),this.G=null)}ed(){return ca&&"cordova"===this.C}oc(){const a=navigator.userAgent;return ca&&na.has(this.C)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}le(){return x}cd(){return x&&na.has(this.C)}async ld(a){"macos-wkwebview"===this.C&&this.Oe();if("playable-ad"===this.C){this.ma=self.c3_base64files;this.Sb={};await this.we();
for(let d=0,e=a.Va.length;d<e;++d){var c=a.Va[d].toLowerCase();this.Sb.hasOwnProperty(c)?a.Va[d]={cf:!0,gf:this.Sb[c]}:this.ma.hasOwnProperty(c)&&(a.Va[d]=URL.createObjectURL(this.ma[c]))}}a.ef?this.ba=a.ef:(c=location.origin,this.ba=("null"===c?"file:///":c)+location.pathname,c=this.ba.lastIndexOf("/"),-1!==c&&(this.ba=this.ba.substr(0,c+1)));a.lf&&(this.yb=a.lf);c=new MessageChannel;this.ta=c.port1;this.ta.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>
this.He(d));this.mb=new self.ne(this);await pa(this.mb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.da?await this.De(a,c.port2):await this.Ce(a,c.port2)}vc(a){a=this.yb.hasOwnProperty(a)?this.yb[a]:a.endsWith("/workermain.js")&&this.yb.hasOwnProperty("workermain.js")?this.yb["workermain.js"]:
"playable-ad"===this.C&&this.ma.hasOwnProperty(a.toLowerCase())?this.ma[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async jc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.C&&this.Ob)return a=await this.Ab(d.bf?a:this.dc+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}ra(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}jd(a){var c=this.ba,d=location.href,e=this.ra(),f=this.ja(),g=window.devicePixelRatio,h=b.Za(),m=a.rf,p=window.cr_previewImageBlobs||this.ma,q=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,y=window.pf||"";a=a.Td;var Y=(new URLSearchParams(self.location.search)).has("debug"),D=this.mb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:t,swClientId:y,exportType:a,isDebug:Y,ife:!!self.qf,jobScheduler:{inputPort:D.Kc,outputPort:D.Qc,maxNumWorkers:D.Ue},supportedAudioFormats:ia,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.dc+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.dc+"opus.wasm.wasm",isFileProtocol:this.Ob,isiOSCordova:this.ed(),isiOSWebView:this.oc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async De(a,
c){var d=this.vc(a.kf);this.xb=await this.jc(d,this.ba,{type:"module",name:"Runtime",bf:!0});this.G=document.createElement("canvas");this.G.style.display="none";d=this.G.transferControlToOffscreen();document.body.appendChild(this.G);window.c3canvas=this.G;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.Vc||[],f=a.Va;e=await Promise.all(e.map(g=>this.Ia(g)));f=await Promise.all(f.map(g=>this.Ia(g)));if("cordova"===this.C)for(let g=0,h=a.hc.length;g<h;++g){const m=a.hc[g],p=
m[0];if(p===a.Tc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))m[1]=await this.Ia(p)}this.xb.postMessage(Object.assign(this.jd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,workerDependencyScripts:e,engineScripts:f,projectScripts:a.hc,mainProjectScript:a.Tc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...qa(this.mb)]);this.Lb=E.map(g=>new g(this));this.hd();self.c3_callFunction=(g,h)=>{var m=this.Sa;return m.u.fd(m.fb,"js-invoke-function",{name:g,params:h},
void 0,void 0)};"preview"===this.C&&(self.goToLastErrorScript=()=>this.Db("runtime","go-to-last-error-script"))}async Ce(a,c){this.G=document.createElement("canvas");this.G.style.display="none";document.body.appendChild(this.G);window.c3canvas=this.G;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Lb=E.map(g=>new g(this));this.hd();var d=a.Va.map(g=>"string"===typeof g?(new URL(g,this.ba)).toString():g);Array.isArray(a.Vc)&&d.unshift(...a.Vc);d=await Promise.all(d.map(g=>this.Ia(g)));
await Promise.all(d.map(g=>z(g)));d=self.C3_ProjectScriptsStatus;const e=a.Tc,f=a.hc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ia(h),await z(h),"preview"!==this.C||d[g]||this.od(g,"main script did not run to completion")}catch(m){this.od(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ia(h),await z(h);"preview"===this.C&&"object"!==typeof self.mf.nf?(this.Hb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.jd(a),{isInWorker:!1,messagePort:c,canvas:this.G,runOnStartupFunctions:ma}),this.nd(),this.Na=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Na,a))}od(a,c){this.Hb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}nd(){this.Hb()}Hb(){const a=
window.$e;a&&(a.parentElement.removeChild(a),window.$e=null)}async Fe(){const a=await ra(this.mb);return{outputPort:a,transferables:[a]}}Ae(){if(this.da)throw Error("not available in worker mode");return this.Na}Db(a,c,d,e,f){this.ta.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}fd(a,c,d,e,f){const g=la++,h=new Promise((m,p)=>{G.set(g,{resolve:m,reject:p})});this.ta.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.Ge(a);if("result"===c)this.Je(a);else if("runtime-ready"===c)this.Ke();else if("alert-error"===c)this.Hb(),alert(a.message);else if("creating-runtime"===c)this.nd();else throw Error(`unknown message '${c}'`);}Ge(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=F.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Gb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Gb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Gb(f,!1,""+h)}):this.Gb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Gb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.ta.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Je(a){const c=a.responseId,d=a.isOk;a=a.result;const e=G.get(c);d?e.resolve(a):e.reject(a);G.delete(c)}D(a,
c,d){let e=F.get(a);e||(e=new Map,F.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static zb(a){if(E.includes(a))throw Error("DOM handler already added");E.push(a)}hd(){for(const a of this.Lb)if("runtime"===a.fb){this.Sa=a;return}throw Error("cannot find runtime DOM handler");}He(a){this.Db("debugger","message",a)}Ke(){for(const a of this.Lb)a.Wc()}static Za(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
oa)}static pd(a){oa=!!a}te(a){this.Qa.push(a);this.Ac()}Me(a){a=this.Qa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Qa.splice(a,1);this.Qa.length||this.tc()}Ac(){-1===this.Ra&&this.Qa.length&&(this.Ra=requestAnimationFrame(this.Xe))}tc(){-1!==this.Ra&&(cancelAnimationFrame(this.Ra),this.Ra=-1)}Ie(){this.Ra=-1;for(const a of this.Qa)a();this.Ac()}ya(a){this.Sa.ya(a)}Ha(a){this.Sa.Ha(a)}zc(){this.Sa.zc()}Fb(a){this.Sa.Fb(a)}me(){return!!ia["audio/webm; codecs=opus"]}async Pe(a){a=await this.fd("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}re(a){this.Lc=!0;this.xd=a}ke(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}dd(a){return!this.ke(a)}async Ia(a){return"cordova"===this.C&&(a.startsWith("file:")||this.Ob&&this.dd(a))?(a.startsWith(this.ba)&&(a=a.substr(this.ba.length)),a=await this.Ab(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async Ee(a){const c=a.filename;switch(a.as){case "text":return await this.ie(c);
case "buffer":return await this.Ab(c);default:throw Error("unsupported type");}}kd(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}md(a,c){a=a[c];if("string"!==typeof a)throw Error("Invalid permission name");return a}Be(a){const c=this.kd();return new Promise((d,e)=>c.checkPermission(this.md(c,a),f=>d(!!f.hasPermission),e))}Ne(a){const c=this.kd();return new Promise((d,e)=>c.requestPermission(this.md(c,
a),f=>d(!!f.hasPermission),e))}async qe(a){if("cordova"!==this.C||this.ed())return!0;for(const c of a)if(!await this.Be(c)&&!1===await this.Ne(c))return!1;return!0}async pc(...a){if(!1===await this.qe(a))throw Error("Permission not granted");}Zc(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async ie(a){a=await this.Zc(a);return await ja(a)}uc(){if(B.length&&!(8<=C)){C++;var a=B.shift();
this.xe(a.filename,a.hf,a.af)}}Ab(a){return new Promise((c,d)=>{B.push({filename:a,hf:e=>{C--;this.uc();c(e)},af:e=>{C--;this.uc();d(e)}});this.uc()})}async xe(a,c,d){try{const e=await this.Zc(a),f=await ka(e);c(f)}catch(e){d(e)}}Oe(){var a={type:"ready"};if("windows-webview2"===this.C)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.C)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async we(){const a=
[];for(const [c,d]of Object.entries(this.ma))a.push(this.ve(c,d));await Promise.all(a)}async ve(a,c){if("object"===typeof c)this.ma[a]=new Blob([c.str],{type:c.type}),this.Sb[a]=c.str;else{let d=await this.ze(c);d||(d=this.ye(c));this.ma[a]=d}}async ze(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
c),null}}ye(a){a=this.Le(a);return this.ue(a.data,a.df)}Le(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{df:a,data:d}}ue(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=
3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const H=self.ab;function sa(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ta=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),I={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},ua={dispatchUserScriptEvent:!0},J={dispatchRuntimeEvent:!0};
function va(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function wa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function K(b){b=URL.createObjectURL(b);try{return await wa(b)}finally{URL.revokeObjectURL(b)}}
function xa(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function ya(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await K(b);var d=await xa(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await K(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await K(b)}
function za(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Aa=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);function L(b){Ba.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ca(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await K(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await ya(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let Da=!1;document.addEventListener("pause",()=>Da=!0);document.addEventListener("resume",()=>Da=!1);async function Ea(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Fa(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ga(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ia(b){self.setTimeout(()=>{b.wd=!0},1E3);"cordova"===b.u.C?(document.addEventListener("pause",()=>Ja(b,!0)),document.addEventListener("resume",()=>Ja(b,!1))):document.addEventListener("visibilitychange",()=>Ja(b,document.hidden));return{isSuspended:!(!document.hidden&&!Da)}}
function Ka(b){b.rd||(b.rd=!0,window.addEventListener("deviceorientation",a=>{b.Z||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},I)}),window.addEventListener("deviceorientationabsolute",a=>{b.Z||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},I)}))}
function La(b){b.qd||(b.qd=!0,window.addEventListener("devicemotion",a=>{if(!b.Z){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},I)}}))}async function Ma(b){await va(b.url)}
function Na(b,a){b.yd=a.message;-1===b.Gc&&(b.Gc=setTimeout(()=>{b.Gc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.yd)},250))}function M(b){if(!b.Z){var a=H.Za();a&&"any"!==b.Rc&&Oa(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ra(),innerHeight:b.ja()})}}function Pa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:H.Za(),innerWidth:b.ra(),innerHeight:b.ja()})}
function Ja(b,a){a?b.u.tc():b.u.Ac();k(b,"visibilitychange",{hidden:a})}function Qa(b,a,c){"Backspace"===c.key&&L(c);if(!b.Z){var d=ta.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},I)}}
function Ra(b,a,c,d){b.Z||sa(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.$,pageX:c.pageX,pageY:c.pageY+b.$,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Sa(b){window!==window.top&&window.focus();Ta(b.target)&&document.activeElement&&!Ta(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.Z){if(b.ub&&"pointermove"!==a){var d=b.ub;d.kb||(aa(d),d.Pb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.rb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.$,pageX:c.pageX,pageY:c.pageY+b.$,movementX:(c.movementX||0)+b.Zb,movementY:(c.movementY||0)+b.$b,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},I);b.Zb=0;b.$b=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Ra(b,d,c,ua),b.rb=c.buttons)}}
function Ua(b,a,c){if(!b.Z&&!sa(c)){var d=b.rb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.$,pageX:c.pageX,pageY:c.pageY+b.$,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},I);b.rb=c.buttons;Ra(b,c.type,c,ua)}}
function O(b,a,c){if(!b.Z)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.$,pageX:f.pageX,pageY:f.pageY+b.$,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
I)}}function Va(b,a,c){document.body.style.transform="";b.$=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.$=a))}}function Xa(b,a,c,d){const e=b.ra(),f=b.ja();b.Ta=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.Za()}):10>d&&Ya(b,e,f,d+1)}
function Ya(b,a,c,d){-1!==b.Ta&&clearTimeout(b.Ta);b.Ta=setTimeout(()=>Xa(b,a,c,d),48)}
function Oa(b){b=b.Rc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ta(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
H.zb(class extends self.Bb{constructor(b){super(b,"runtime");this.Dd=!0;this.Ta=-1;this.Rc="any";this.qd=this.rd=!1;this.Ba=null;this.Z=!1;this.yd="";this.Gc=-1;this.Ma=this.ub=null;this.$b=this.Zb=0;this.wd=!1;this.Hd=b.ra();this.Qb=b.ja();this.$=this.wb=0;b.D("canvas","update-size",d=>{var e=this.u;e.Lc||(e=e.G,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.Dd&&(e.style.display="",this.Dd=!1))});b.D("runtime",
"invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.D("runtime","raster-svg-image",d=>Ea(d));b.D("runtime","get-svg-image-size",d=>Fa(d));b.D("runtime","set-target-orientation",d=>{this.Rc=d.targetOrientation});b.D("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.D("runtime","post-to-debugger",d=>Ga(d));b.D("runtime","go-to-script",d=>
Ga(d));b.D("runtime","before-start-ticking",()=>Ia(this));b.D("runtime","debug-highlight",d=>{if(d.show){this.Ba||(this.Ba=document.createElement("div"),this.Ba.id="inspectOutline",document.body.appendChild(this.Ba));var e=this.Ba;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ba&&(this.Ba.style.display="none")});b.D("runtime","enable-device-orientation",()=>Ka(this));b.D("runtime","enable-device-motion",
()=>La(this));b.D("runtime","add-stylesheet",d=>Ma(d));b.D("runtime","alert",d=>{alert(d.message)});b.D("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.D("runtime","set-exporting-to-video",d=>{this.Z=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.u.G.style.display="";this.u.re(d.duration)});b.D("runtime",
"export-to-video-progress",d=>Na(this,d));b.D("runtime","exported-to-video",d=>{window.Ze({type:"exported-video",blob:d.blob,time:d.time})});b.D("runtime","exported-to-image-sequence",d=>{window.Ze({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||za(e)||d.preventDefault()});const c=b.G;window.addEventListener("selectstart",L);window.addEventListener("gesturehold",
L);c.addEventListener("selectstart",L);c.addEventListener("gesturehold",L);window.addEventListener("touchstart",L,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",L,{passive:!1}),c.addEventListener("pointerdown",L)):c.addEventListener("touchstart",L);this.rb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",
()=>{a:{if(!this.Z){var d=this.ra();var e=this.ja();if(this.u.cd()){if(this.wd){if(this.Hd===d&&e<this.Qb){this.wb=this.Qb-e;Va(this,this.Qb,this.wb);d=void 0;break a}0<this.wb&&(this.wb=0,Va(this,e,this.wb))}this.Hd=d;this.Qb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:H.Za()});this.u.oc()&&(-1!==this.Ta&&clearTimeout(this.Ta),Xa(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",
()=>M(this));window.addEventListener("mozfullscreenchange",()=>M(this));window.addEventListener("fullscreenerror",d=>Pa(this,d));window.addEventListener("webkitfullscreenerror",d=>Pa(this,d));window.addEventListener("mozfullscreenerror",d=>Pa(this,d));if(b.oc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;
if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):za(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(H.pd(!0),M(this)):"exited-fullscreen"===d?(H.pd(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Oa=new Set;this.Ub=new WeakSet;this.sa=!1}Wc(){window.addEventListener("focus",()=>{k(this,"window-focus",
null,J)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},J);this.rb=0});window.addEventListener("focusin",a=>{a=a.target;(Aa.has(a.tagName.toLowerCase())||za(a))&&k(this,"keyboard-blur",null,J)});window.addEventListener("keydown",a=>Qa(this,"keydown",a));window.addEventListener("keyup",a=>Qa(this,"keyup",a));window.addEventListener("dblclick",a=>Ra(this,"dblclick",a,I));window.addEventListener("wheel",
a=>{this.Z||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.$,pageX:a.pageX,pageY:a.pageY+this.$,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},I)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Sa(a);N(this,"pointerdown",a)}),this.u.da&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.ub=new self.pe(()=>{N(this,"pointermove",this.Ma);this.Ma=null}),this.ub.ud=!0,window.addEventListener("pointerrawupdate",
a=>{this.Ma&&(this.Zb+=this.Ma.movementX||0,this.$b+=this.Ma.movementY||0);this.Ma=a;a=this.ub;if(-1===a.Ua){var c=Date.now(),d=c-a.Pb,e=a.Re;d>=e&&a.ud?(a.Pb=c,a.kb=!0,a.Dc(),a.kb=!1):a.Ua=self.setTimeout(a.Sd,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Sa(a);Ua(this,"pointerdown",a)}),
window.addEventListener("mousemove",a=>Ua(this,"pointermove",a)),window.addEventListener("mouseup",a=>Ua(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Sa(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=()=>this.zc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",
b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.u.le()&&!this.u.cd()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Va(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}ra(){return this.u.ra()}ja(){return this.u.ja()}zc(){var b=[...this.Oa];this.Oa.clear();if(!this.sa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Ub.has(a)||this.Oa.add(a)})}ya(b){if("function"!==
typeof b.play)throw Error("missing play function");this.Ub.delete(b);let a;try{a=b.play()}catch(c){this.Oa.add(b);return}a&&a.catch(()=>{this.Ub.has(b)||this.Oa.add(b)})}Ha(b){this.Oa.delete(b);this.Ub.add(b)}Fb(b){this.sa=!!b}});"use strict";
async function pa(b){if(b.Qe)throw Error("already initialised");b.Qe=!0;var a=b.cc.vc("dispatchworker.js");b.Fc=await b.cc.jc(a,b.eb,{name:"DispatchWorker"});a=new MessageChannel;b.Kc=a.port1;b.Fc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Qc=await ra(b)}function qa(b){return[b.Kc,b.Qc]}
async function ra(b){const a=b.Ed.length;var c=b.cc.vc("jobworker.js");c=await b.cc.jc(c,b.eb,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Fc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.Ed.push(c);return e.port1}
self.ne=class{constructor(b){this.cc=b;this.eb=b.ba;this.eb="preview"===b.C?this.eb+"workers/":this.eb+b.dc;this.Ue=Math.min(navigator.hardwareConcurrency||2,16);this.Fc=null;this.Ed=[];this.Qc=this.Kc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ab({jf:!0,kf:"workermain.js",Va:["scripts/c3runtime.js"],hc:[],Tc:"",ff:"scripts/",Vc:[],Td:"html5"}));"use strict";
async function Za(){const b=[],a=[];if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){var c=await navigator.mediaDevices.enumerateDevices();for(const d of c){c=d.kind;const e={deviceId:d.deviceId,label:d.label,facing:d.facing||d.facingMode||""};"video"===c||"videoinput"===c?b.push(e):("audio"===c||"audioinput"===c)&&a.push(e)}}return{videoSources:b,audioSources:a}}
async function $a(b,a,c){try{const d=b.u;"object"===typeof c.constraints.audio?await d.pc("CAMERA","RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"):await d.pc("CAMERA");b.Ca=await navigator.mediaDevices.getUserMedia(c.constraints);a.srcObject=b.Ca;a.play();u(b);return{ok:!0}}catch(d){return console.warn("Error requesting camera: ",d),{ok:!1}}}
async function bb(b,a){try{return await b.u.pc("RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"),b.Ca=await navigator.mediaDevices.getUserMedia(a.constraints),self.C3Audio_OnMicrophoneStream&&self.C3Audio_OnMicrophoneStream(b.Ca,a.tag),{ok:!0}}catch(c){return console.warn("Error requesting microphone: ",c),{ok:!1}}}
async function cb(b,a){const c=document.createElement("canvas");c.width=b.videoWidth;c.height=b.videoHeight;c.getContext("2d").drawImage(b,0,0,b.videoWidth,b.videoHeight);return{snapshotUrl:await db(c,a.format,a.quality)}}function eb(b,a){b.Ca===a&&(b.Ca=null);b=a.getTracks();for(let c=0,d=b.length;c<d;++c)b[c].stop()}function db(b,a,c){return new Promise(d=>{b.toBlob?b.toBlob(e=>d(URL.createObjectURL(e)),a,c):d(b.toDataURL(a,c))})}
self.ab.zb(class extends self.je{constructor(b){super(b);this.cb=!1;this.Te=this.u.da;this.Ye=0;this.Ca=null;n(this,"get-media-sources",()=>Za());w(this,"request-camera",(a,c)=>$a(this,a,c));w(this,"request-microphone",(a,c)=>bb(this,c));w(this,"snapshot",(a,c)=>cb(a,c));w(this,"stop",a=>this.Bc(a));self.C3UserMedia_GetVideoElement=a=>this.W.get(a);self.C3UserMedia_GetLastMediaStream=()=>this.Ca}$c(b){const a=document.createElement("video");a.crossOrigin="anonymous";a.autoplay=!0;a.muted=!0;a.playsInline=
!0;a.addEventListener("canplaythrough",()=>{v(this,"video-ready",b,{width:a.videoWidth,height:a.videoHeight})});return a}gd(){}bd(b){b.srcObject&&(eb(this,b.srcObject),b.srcObject=null)}Bc(b){b.srcObject&&(eb(this,b.srcObject),b.srcObject=null)}xa(){const b={},a={sequenceNumber:this.Ye++,videoData:b},c=[],d=[];for(const [e,f]of this.W.entries()){if(!f.srcObject)continue;const g={width:f.videoWidth,height:f.videoHeight};this.Te&&d.push(createImageBitmap(f).then(h=>{g.imageBitmap=h;c.push(h)}).catch(()=>
{g.imageBitmap=null}));b[e.toString()]=g}Promise.all(d).then(()=>k(this,"state",a,!1,c))}});"use strict";const fb=180/Math.PI;
async function gb(b,a){a.isiOSCordova&&(b.Xb=!0);b.Sc=a.timeScaleMode;b.Kd=["equalpower","HRTF","soundfield"][a.panningModel];b.vd=["linear","inverse","exponential"][a.distanceModel];b.Ld=a.refDistance;b.Jd=a.maxDistance;b.Nd=a.rolloffFactor;if(b.u.Lc)b.Xb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.u.xd)});else{var c={latencyHint:a.latencyHint};b.Qd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");hb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&hb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ka=b.g.createGain();b.Ka.connect(b.g.destination);c=a.listenerPos;b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",
d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function ib(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.Fd=g;jb(b,g);try{b.la=await kb(b,c,d,e,g,f);if(q){Q(b.la,!0);var y=b.la,Y=q.innerAngle,D=q.outerAngle,wb=q.outerGain;if(y.lb){lb(y,q.x,q.y,q.angle);var Ha=self.Wa.se;y.F.coneInnerAngle=Ha(Y);y.F.coneOuterAngle=
Ha(D);y.F.coneOuterGain=wb}q.hasOwnProperty("uid")&&(b.la.ka=q.uid)}else Q(b.la,!1);b.la.Play(h,m,p,t)}catch(xb){console.error("[Construct] Audio: error starting playback: ",xb);return}finally{c=b.tb.get(g);if(!c)throw Error("expected pending tag");c.Uc--;0===c.Uc&&(c.resolve(),b.tb.delete(g))}u(b)}
async function mb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await nb(b,c);for(const q of R(b,c)){c=q;var f=d,g=e,h=a;if(!c.La){var m=c.N.gain;m.cancelScheduledValues(0);var p=c.s.g.currentTime;g=p+g;m.setValueAtTime(m.value,p);m.linearRampToValueAtTime(f,g);c.Fa=f;c.ib=g;c.Pd=h}}S(b)}async function ob(b,a){const c=a.tag;a=a.rate;await nb(b,c);for(const d of R(b,c))b=d,b.ia!==a&&(b.ia=a,b.za())}
async function pb(b,a){const c=a.tag;a=a.pos;await nb(b,c);for(const d of R(b,c))d.qc(a)}async function qb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await kb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function rb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ga.indexOf(a),-1!==a&&b.ga.splice(a,1)}
async function sb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Zd(b,...e);else if("delay"===c)e=new self.Xd(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Wd(b,c.fa,...e);var f=a.bufferType;c.sd=a.bufferOriginalUrl;c.td=f}else if("flanger"===c)e=new self.$d(b,...e);else if("phaser"===c)e=new self.be(b,...e);else if("gain"===c)e=
new self.ae(b,...e);else if("tremolo"===c)e=new self.de(b,...e);else if("ringmod"===c)e=new self.ce(b,...e);else if("distortion"===c)e=new self.Yd(b,...e);else if("compressor"===c)e=new self.Vd(b,...e);else if("analyser"===c)e=new self.Ud(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.ha.get(d);e||(e=[],b.ha.set(d,e));a.Cd=e.length;a.ca=d;e.push(a);tb(b,d);ub(b)}
async function vb(b,a){const c=a.saveLoadMode;if(3!==c)for(var d of b.L)d.wa()&&1===c||(d.wa()||2!==c)&&d.qa();for(const e of b.ha.values())for(const f of e)f.j();b.ha.clear();b.ec=a.timeScale;b.Hc=a.gameTime;d=a.listenerPos;b.g.listener.setPosition(d[0],d[1],d[2]);b.sa=a.isSilent;b.u.Fb(b.sa);b.Tb=a.masterVolume;b.Ka.gain.value=b.Tb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>sb(b,f))));await Promise.all(d);await Promise.all(a.playing.map(e=>yb(b,e,c)));S(b)}
async function zb(b,a){try{const c=b.g.suspend(a.time);b.Bd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.u.Db("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>Ab(d)),b.Bd=!0);await c}catch(c){Ab(c)}}
function hb(b){b.Mb||(b.Jc=!1,window.addEventListener("pointerup",b.ua,!0),window.addEventListener("touchend",b.ua,!0),window.addEventListener("click",b.ua,!0),window.addEventListener("keydown",b.ua,!0),b.Mb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ga)if(g.Ya()===c)return await Cb(g),g;if(f)return null;if(e&&(b.Xb||b.Ad)){f=0;for(let h=0,m=b.ga.length;h<m;++h)g=b.ga[h],b.ga[f]=g,g.wa()?g.j():++f;b.ga.length=f}f="audio/webm; codecs=opus"===d&&!b.Qd;e&&f&&(b.Ad=!0);c=!e||b.Xb||f?new self.ge(b,a,c,d,e,f):new self.ee(b,a,c,d,e);b.ga.push(c);await Cb(c);b.Id.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ea()}),b.Id.add(a));return c}
function Db(b,a){return(a=b.ha.get(a.toLowerCase()))?a[0].R():b.va()}function tb(b,a){let c=b.va();var d=b.ha.get(a);if(d&&d.length){c=d[0].R();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.va()):e.U(d[f+1].R())}}for(const f of R(b,a))d=c,e=f.F||f.N,e.disconnect(),e.connect(d);b.Da&&b.Oc===a&&(b.Da.disconnect(),b.Da.connect(c))}function*R(b,a){if(a)for(const c of b.L)b=c.ca,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.la&&!b.la.S()&&(yield b.la)}
function Eb(b,a,c){return c?b.u.Pe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Fb(b,a){let c=0;for(let d=0,e=b.L.length;d<e;++d){const f=b.L[d];b.L[c]=f;f.M===a?f.j():++c}b.L.length=c}async function kb(b,a,c,d,e,f){for(const g of b.L)if(g.Ya()===c&&(g.ic()||f))return g.ca=e,g;a=await P(b,a,c,d,f);e="html5"===a.Cc?new self.fe(a.s,a,e):new self.he(a.s,a,e);b.L.push(e);return e}
function jb(b,a){let c=b.tb.get(a);if(!c){let d=null;c={Uc:0,promise:new Promise(e=>d=e),resolve:d};b.tb.set(a,c)}c.Uc++}function nb(b,a){a||(a=b.Fd);return(b=b.tb.get(a))?b.promise:Promise.resolve()}function S(b){if(0<b.Ja.size)u(b);else for(const a of b.L)if(!a.H&&!a.S()){u(b);break}}function Gb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function ub(b){b.Mc||(b.Mc=!0,Promise.resolve().then(()=>Hb(b)))}
function Hb(b){const a={};for(const [c,d]of b.ha)a[c]=d.map(e=>e.Xa());k(b,"fxstate",{fxstate:a});b.Mc=!1}
async function yb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await kb(b,d,e,f,h,g)}catch(t){console.error("[Construct] Audio: error loading audio state: ",t);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.oa[0]=f[0],b.oa[1]=f[1],b.oa[2]=f[2],f=d.orient,b.na[0]=f[0],b.na[1]=f[1],b.na[2]=f[2],e.setPosition(...b.oa),e.setOrientation(...b.na),e.coneInnerAngle=d.cia,e.coneOuterAngle=
d.coa,e.coneOuterGain=d.cog,b.ka=d.uid):Q(b,!1);c.Play(m,p,q,0);a.isPlaying||c.$a();c.xc(a)}}}function Ab(b){console.error("[Audio] Offline rendering error: ",b)}
self.Wa=class extends self.Bb{constructor(b){super(b,"audio");this.Ka=this.g=null;this.Mb=this.Jc=!1;this.ua=()=>{if(!this.Jc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Mb&&(this.Jc=!0,window.removeEventListener("pointerup",this.ua,!0),window.removeEventListener("touchend",this.ua,!0),window.removeEventListener("click",this.ua,!0),window.removeEventListener("keydown",
this.ua,!0),this.Mb=!1)}};this.ga=[];this.L=[];this.la=null;this.Fd="";this.Id=new Set;this.Gd=-1;this.tb=new Map;this.Tb=1;this.sa=!1;this.Sc=0;this.ec=1;this.Hc=0;this.Kd="HRTF";this.vd="inverse";this.Ld=600;this.Jd=1E4;this.Nd=1;this.Ad=this.Xb=!1;this.Qd=this.u.me();this.ha=new Map;this.Ja=new Set;this.Bd=this.Mc=!1;this.Oc="";this.Da=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Da&&this.Da.disconnect();this.Oc=c.toLowerCase();this.Da=this.g.createMediaStreamSource(a);this.Da.connect(Db(this,
this.Oc))};this.Kb=null;self.C3Audio_GetOutputStream=()=>{this.Kb||(this.Kb=this.g.createMediaStreamDestination(),this.Ka.connect(this.Kb));return this.Kb.stream};self.C3Audio_DOMInterface=this;r(this,[["create-audio-context",a=>gb(this,a)],["play",a=>ib(this,a)],["stop",a=>this.Bc(a)],["stop-all",()=>{for(const a of this.L)a.qa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of R(this,c))a?d.$a():d.Eb();S(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;for(const d of R(this,c))T(d,a)}],
["fade-volume",a=>mb(this,a)],["set-master-volume",a=>{this.Tb=a.vol;this.Ka.gain.value=this.Tb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of R(this,c))Ib(d,a)}],["set-silent",a=>{this.sa=a.isSilent;this.u.Fb(this.sa);for(const c of this.L)c.Ib()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of R(this,c))d.rc(a)}],["set-playback-rate",a=>ob(this,a)],["seek",a=>pb(this,a)],["preload",a=>qb(this,a)],["unload",a=>rb(this,a)],["unload-all",()=>{for(const a of this.ga)a.j();
this.ga.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.L)c.sc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>sb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.ha.get(a.tag);!a||0>c||c>=a.length||(a[c].aa(d,e,f,g),ub(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.ha.get(a);if(c&&c.length){for(const d of c)d.j();this.ha.delete(a);tb(this,a)}}],["tick",a=>{this.ec=a.timeScale;
this.Hc=a.gameTime;this.Gd=a.tickCount;if(0!==this.Sc)for(var c of this.L)c.za();(c=a.listenerPos)&&this.g.listener.setPosition(c[0],c[1],c[2]);for(const d of a.instPans){a=d.uid;for(const e of this.L)e.ka===a&&lb(e,d.x,d.y,d.angle)}}],["load-state",a=>vb(this,a)],["offline-render-audio",a=>zb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}Y(){return this.g}va(){return this.Ka}Cb(){return this.sa}ya(b){this.u.ya(b)}Ha(b){this.u.Ha(b)}xa(){for(var b of this.Ja)b.xa();b=this.g.currentTime;
for(var a of this.L)a.xa(b);a=this.L.filter(c=>!c.H&&!c.S()).map(c=>c.Xa());k(this,"state",{tickCount:this.Gd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ja].map(c=>({tag:c.ca,index:c.Cd,peak:c.Pa,rms:c.Md,binCount:c.m.frequencyBinCount,freqBins:c.zd}))});0===a.length&&0===this.Ja.size&&this.Nb&&(this.u.Me(this.Rd),this.Nb=!1)}Bc(b){b=b.tag;for(const a of R(this,b))a.qa()}static se(b){return b*fb}static ad(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static oe(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.ab.zb(self.Wa);"use strict";function Cb(b){b.Rb||(b.Rb=b.wc());return b.Rb}self.Xc=class{constructor(b,a,c,d,e){this.s=b;this.We=a;this.Ea=c;this.T=d;this.Se=e;this.Cc="";this.Rb=null}j(){this.Rb=this.s=null}wc(){}Y(){return this.s.Y()}lc(){return this.We}Ya(){return this.Ea}kc(){return this.T}wa(){return this.Se}ea(){}};"use strict";
self.ee=class extends self.Xc{constructor(b,a,c,d,e){super(b,a,c,d,e);this.Cc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.nb=this.ob=null;this.K.addEventListener("canplaythrough",()=>!0);this.sb=this.Y().createGain();this.qb=null;this.K.addEventListener("canplay",()=>{this.ob&&(this.ob(),this.nb=this.ob=null);!this.qb&&this.K&&(this.qb=this.Y().createMediaElementSource(this.K),this.qb.connect(this.sb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ea}' error: `,f);this.nb&&(this.nb(f),this.nb=this.ob=null)})}j(){Fb(this.s,this);this.sb.disconnect();this.sb=null;this.qb.disconnect();this.qb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.j()}wc(){return new Promise((b,a)=>{this.ob=b;this.nb=a;this.K.src=this.Ea})}P(){return this.K}ea(){return this.K.duration}};"use strict";
async function Jb(b){if(b.Aa)return b.Aa;var a=b.s.u;if("cordova"===a.C&&a.dd(b.Ea)&&a.Ob)b.Aa=await a.Ab(b.Ea);else{a=await fetch(b.Ea);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Aa=await a.arrayBuffer()}}async function Kb(b){if(b.fa)return b.fa;b.fa=await Eb(b.s,b.Aa,b.Ve);b.Aa=null}
self.ge=class extends self.Xc{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.Cc="webaudio";this.fa=this.Aa=null;this.Ve=!!f}j(){Fb(this.s,this);this.fa=this.Aa=null;super.j()}async wc(){try{await Jb(this),await Kb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ea}': `,b)}}ea(){return this.fa?this.fa.duration:0}};"use strict";let Lb=0;
function Q(b,a){a=!!a;b.lb!==a&&(b.lb=a,b.lb?(b.F||(b.F=b.Y().createPanner(),b.F.panningModel=b.s.Kd,b.F.distanceModel=b.s.vd,b.F.refDistance=b.s.Ld,b.F.maxDistance=b.s.Jd,b.F.rolloffFactor=b.s.Nd),b.N.disconnect(),b.N.connect(b.F),b.F.connect(b.va())):(b.F.disconnect(),b.N.disconnect(),b.N.connect(b.va())))}function T(b,a){b.Fa=a;b.N.gain.cancelScheduledValues(0);b.ib=-1;b.N.gain.value=b.mc()}function Ib(b,a){a=!!a;b.La!==a&&(b.La=a,b.Ib())}
function lb(b,a,c,d){b.lb&&(b.oa[0]=a,b.oa[1]=c,b.oa[2]=0,b.na[0]=Math.cos(d),b.na[1]=Math.sin(d),b.na[2]=0,b.F.setPosition(...b.oa),b.F.setOrientation(...b.na))}function U(b){return b.Nc?b.s.Hc:performance.now()/1E3}
self.Yc=class{constructor(b,a,c){this.s=b;this.M=a;this.ca=c;this.Jb=Lb++;this.N=this.Y().createGain();this.N.connect(this.va());this.F=null;this.lb=!1;this.oa=[0,0,0];this.na=[0,0,0];this.H=!0;this.X=this.pa=this.I=!1;this.Fa=1;this.La=!1;this.ia=1;b=this.s.Sc;this.Nc=1===b&&!this.wa()||2===b;this.ib=this.ka=-1;this.Pd=!1}j(){this.M=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.N.disconnect();this.N=null}Y(){return this.s.Y()}va(){return Db(this.s,this.ca)}lc(){return this.M.lc()}Ya(){return this.M.Ya()}kc(){return this.M.kc()}wa(){return this.M.wa()}S(){}ic(){}IsPlaying(){return!this.H&&
!this.I&&!this.S()}Ga(){}ea(){return this.M.ea()}Play(){}qa(){}$a(){}Eb(){}xa(b){-1!==this.ib&&b>=this.ib&&(this.ib=-1,this.Pd&&this.qa(),Gb(this.s,"fade-ended",this.ca,this.Jb))}mc(){const b=this.Fa;return isFinite(b)?b:0}Cb(){return this.s.Cb()}Ib(){}rc(){}za(){}qc(){}sc(){}nc(){}Xa(){var b=this.Jb,a=this.ca,c=this.ea(),d=this.Fa,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.oa,orient:this.na,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ka}}else f=null;return{aiid:b,
tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Ga(),playbackRate:this.ia,uid:this.ka,bufferOriginalUrl:this.lc(),bufferUrl:"",bufferType:this.kc(),isMusic:this.wa(),isLooping:this.X,isMuted:this.La,resumePosition:this.nc(),pan:f}}xc(b){var a=b.playbackRate;this.ia!==a&&(this.ia=a,this.za());Ib(this,b.isMuted)}};"use strict";
self.fe=class extends self.Yc{constructor(b,a,c){super(b,a,c);this.M.sb.connect(this.N);this.M.onended=()=>this.yc()}j(){this.qa();this.M.sb.disconnect();super.j()}P(){return this.M.P()}yc(){this.H=!0;this.ka=-1;Gb(this.s,"ended",this.ca,this.Jb)}S(){return this.P().ended}ic(){return this.H?!0:this.S()}Ga(){let b=this.P().currentTime;this.X||(b=Math.min(b,this.ea()));return b}Play(b,a,c){const d=this.P();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.M.Ya()}' to position '${c}': `,e)}this.s.ya(d);this.I=this.H=!1;this.X=b;this.ia=1}qa(){const b=this.P();b.paused||b.pause();this.s.Ha(b);this.H=!0;this.I=!1;this.ka=-1}$a(){if(!(this.I||this.H||this.S())){var b=this.P();b.paused||b.pause();this.s.Ha(b);this.I=!0}}Eb(){!this.I||this.H||this.S()||(this.s.ya(this.P()),this.I=!1)}Ib(){this.P().muted=this.La||this.Cb()}rc(b){b=!!b;this.X!==b&&(this.X=
b,this.P().loop=b)}za(){let b=this.ia;this.Nc&&(b*=this.s.ec);try{this.P().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}qc(b){if(!this.H&&!this.S())try{this.P().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}nc(){return this.Ga()}sc(b){b?this.IsPlaying()?(this.P().pause(),this.pa=!0):this.pa=!1:this.pa&&(this.s.ya(this.P()),this.pa=!1)}};"use strict";function V(b){b.o&&b.o.disconnect();b.o=null;b.bb=null}
self.he=class extends self.Yc{constructor(b,a,c){super(b,a,c);this.o=null;this.Vb=d=>this.yc(d);this.Ic=!0;this.bb=null;this.O=this.Wb=this.Yb=0;this.Pc=1}j(){this.qa();V(this);this.Vb=null;super.j()}yc(b){this.I||this.pa||b.target!==this.bb||(this.H=this.Ic=!0,this.ka=-1,V(this),Gb(this.s,"ended",this.ca,this.Jb))}S(){return!this.H&&this.o&&this.o.loop||this.I?!1:this.Ic}ic(){return!this.o||this.H?!0:this.S()}Ga(){let b;b=this.I?this.O:this.Wb+(U(this)-this.Yb)*this.ia;this.X||(b=Math.min(b,this.ea()));
return b}Play(b,a,c,d){this.Pc=1;T(this,a);V(this);this.o=this.Y().createBufferSource();this.o.buffer=this.M.fa;this.o.connect(this.N);this.bb=this.o;this.o.onended=this.Vb;this.o.loop=b;this.o.start(d,c);this.I=this.H=this.Ic=!1;this.X=b;this.ia=1;this.Yb=U(this);this.Wb=c}qa(){if(this.o)try{this.o.stop(0)}catch(b){}this.H=!0;this.I=!1;this.ka=-1}$a(){this.I||this.H||this.S()||(this.O=this.Ga(),this.X&&(this.O%=this.ea()),this.I=!0,this.o.stop(0))}Eb(){!this.I||this.H||this.S()||(V(this),this.o=
this.Y().createBufferSource(),this.o.buffer=this.M.fa,this.o.connect(this.N),this.bb=this.o,this.o.onended=this.Vb,this.o.loop=this.X,T(this,this.Fa),this.za(),this.o.start(0,this.O),this.Yb=U(this),this.Wb=this.O,this.I=!1)}mc(){return super.mc()*this.Pc}Ib(){this.Pc=this.La||this.Cb()?0:1;T(this,this.Fa)}rc(b){b=!!b;this.X!==b&&(this.X=b,this.o&&(this.o.loop=b))}za(){let b=this.ia;this.Nc&&(b*=this.s.ec);this.o&&(this.o.playbackRate.value=b)}qc(b){this.H||this.S()||(this.I?this.O=b:(this.$a(),this.O=
b,this.Eb()))}nc(){return this.O}sc(b){b?this.IsPlaying()?(this.pa=!0,this.O=this.Ga(),this.X&&(this.O%=this.ea()),this.o.stop(0)):this.pa=!1:this.pa&&(V(this),this.o=this.Y().createBufferSource(),this.o.buffer=this.M.fa,this.o.connect(this.N),this.bb=this.o,this.o.onended=this.Vb,this.o.loop=this.X,T(this,this.Fa),this.za(),this.o.start(0,this.O),this.Yb=U(this),this.Wb=this.O,this.pa=!1)}xc(b){super.xc(b);this.O=b.resumePosition}};"use strict";function W(b){return b.g.createGain()}
function X(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.Y();this.Cd=-1;this.T=this.ca="";this.l=null}j(){this.g=null}R(){}U(){}Xa(){return{type:this.T,tag:this.ca,params:this.l}}}
self.Zd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.l=[a,c,d,e,f,g];this.v=W(this);this.i=W(this);this.i.gain.value=g;this.h=W(this);this.h.gain.value=1-g;this.B=this.g.createBiquadFilter();this.B.type=a;this.B.frequency.value=c;this.B.detune.value=d;this.B.Q.value=e;this.B.gain.vlaue=f;this.v.connect(this.B);this.v.connect(this.h);this.B.connect(this.i)}j(){this.v.disconnect();this.B.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 1:this.l[1]=a;X(this,this.B.frequency,a,c,d);break;case 2:this.l[2]=a;X(this,this.B.detune,a,c,d);break;case 3:this.l[3]=a;X(this,this.B.Q,a,c,d);break;case 4:this.l[4]=a,X(this,this.B.gain,a,c,d)}}};
self.Xd=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.l=[a,c,d];this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.pb=W(this);this.V=this.g.createDelay(a);this.V.delayTime.value=a;this.hb=W(this);this.hb.gain.value=c;this.v.connect(this.pb);this.v.connect(this.h);this.pb.connect(this.i);this.pb.connect(this.V);this.V.connect(this.hb);this.hb.connect(this.pb)}j(){this.v.disconnect();this.i.disconnect();this.h.disconnect();this.pb.disconnect();
this.V.disconnect();this.hb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}aa(b,a,c,d){const e=self.Wa.ad;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[2]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 4:this.l[1]=e(a);X(this,this.hb.gain,e(a),c,d);break;case 5:this.l[0]=a,X(this,this.V.delayTime,a,c,d)}}};
self.Wd=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.l=[c,d];this.td=this.sd="";this.v=W(this);this.i=W(this);this.i.gain.value=d;this.h=W(this);this.h.gain.value=1-d;this.gb=this.g.createConvolver();this.gb.normalize=c;this.gb.buffer=a;this.v.connect(this.gb);this.v.connect(this.h);this.gb.connect(this.i)}j(){this.v.disconnect();this.gb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}aa(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[1]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,1-a,c,d)}}Xa(){const b=super.Xa();b.bufferOriginalUrl=this.sd;b.bufferUrl="";b.bufferType=this.td;return b}};
self.$d=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.l=[a,c,d,e,f];this.v=W(this);this.h=W(this);this.h.gain.value=1-f/2;this.i=W(this);this.i.gain.value=f/2;this.jb=W(this);this.jb.gain.value=e;this.V=this.g.createDelay(a+c);this.V.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.J=W(this);this.J.gain.value=c;this.v.connect(this.V);this.v.connect(this.h);this.V.connect(this.i);this.V.connect(this.jb);this.jb.connect(this.V);this.A.connect(this.J);
this.J.connect(this.V.delayTime);this.A.start(0)}j(){this.A.stop(0);this.v.disconnect();this.V.disconnect();this.A.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();this.jb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[4]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 6:this.l[1]=a/1E3;X(this,this.J.gain,a/1E3,
c,d);break;case 7:this.l[2]=a;X(this,this.A.frequency,a,c,d);break;case 8:this.l[3]=a/100,X(this,this.jb.gain,a/100,c,d)}}};
self.be=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.l=[a,c,d,e,f,g];this.v=W(this);this.h=W(this);this.h.gain.value=1-g/2;this.i=W(this);this.i.gain.value=g/2;this.B=this.g.createBiquadFilter();this.B.type="allpass";this.B.frequency.value=a;this.B.detune.value=c;this.B.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.J=W(this);this.J.gain.value=e;this.v.connect(this.B);this.v.connect(this.h);this.B.connect(this.i);this.A.connect(this.J);this.J.connect(this.B.frequency);
this.A.start(0)}j(){this.A.stop(0);this.v.disconnect();this.B.disconnect();this.A.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;X(this,this.i.gain,a/2,c,d);X(this,this.h.gain,1-a/2,c,d);break;case 1:this.l[0]=a;X(this,this.B.frequency,a,c,d);break;case 2:this.l[1]=a;X(this,this.B.detune,a,c,
d);break;case 3:this.l[2]=a;X(this,this.B.Q,a,c,d);break;case 6:this.l[3]=a;X(this,this.J.gain,a,c,d);break;case 7:this.l[4]=a,X(this,this.A.frequency,a,c,d)}}};self.ae=class extends Z{constructor(b,a){super(b);this.T="gain";this.l=[a];this.m=W(this);this.m.gain.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}aa(b,a,c,d){const e=self.Wa.ad;switch(b){case 4:this.l[0]=e(a),X(this,this.m.gain,e(a),c,d)}}};
self.de=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.l=[a,c];this.m=W(this);this.m.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.J=W(this);this.J.gain.value=c/2;this.A.connect(this.J);this.J.connect(this.m.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.J.disconnect();this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=
a;X(this,this.m.gain,1-a/2,c,d);X(this,this.J.gain,a/2,c,d);break;case 7:this.l[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.ce=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.l=[a,c];this.v=W(this);this.i=W(this);this.i.gain.value=c;this.h=W(this);this.h.gain.value=1-c;this.vb=W(this);this.vb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.vb.gain);this.A.start(0);this.v.connect(this.vb);this.v.connect(this.h);this.vb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.vb.disconnect();this.v.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=a;X(this,this.i.gain,a,c,d);X(this,this.h.gain,1-a,c,d);break;case 7:this.l[0]=a,X(this,this.A.frequency,a,c,d)}}};
self.Yd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.l=[a,c,d,e,f];this.v=W(this);this.bc=W(this);this.ac=W(this);b=d;.01>b&&(b=.01);this.bc.gain.value=b;this.ac.gain.value=Math.pow(1/b,.6)*e;this.i=W(this);this.i.gain.value=f;this.h=W(this);this.h.gain.value=1-f;this.fc=this.g.createWaveShaper();this.Ec=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ec[32768+e]=f,this.Ec[32768-
e-1]=-f;this.fc.curve=this.Ec;this.v.connect(this.bc);this.v.connect(this.h);this.bc.connect(this.fc);this.fc.connect(this.ac);this.ac.connect(this.i)}j(){this.v.disconnect();this.bc.disconnect();this.fc.disconnect();this.ac.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.v}aa(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[4]=a,X(this,this.i.gain,a,c,d),X(this,this.h.gain,
1-a,c,d)}}};self.Vd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.l=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}aa(){}};
self.Ud=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.l=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.zd=new Float32Array(this.m.frequencyBinCount);this.Od=new Uint8Array(a);this.Md=this.Pa=0;b=this.s;b.Ja.add(this);S(b)}j(){this.s.Ja.delete(this);this.m.disconnect();super.j()}xa(){this.m.getFloatFrequencyData(this.zd);this.m.getByteTimeDomainData(this.Od);const b=this.m.fftSize;let a=this.Pa=0;for(var c=0;c<b;++c){let d=(this.Od[c]-
128)/128;0>d&&(d=-d);this.Pa<d&&(this.Pa=d);a+=d*d}c=self.Wa.oe;this.Pa=c(this.Pa);this.Md=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}aa(){}};"use strict";
self.ab.zb(class extends self.Bb{constructor(b){super(b,"mouse");r(this,[["cursor",a=>{document.documentElement.style.cursor=a}],["request-pointer-lock",()=>{this.u.G.requestPointerLock()}],["release-pointer-lock",()=>{document.exitPointerLock()}]]);document.addEventListener("pointerlockchange",()=>{k(this,"pointer-lock-change",{"has-pointer-lock":!!document.pointerLockElement})});document.addEventListener("pointerlockerror",()=>{k(this,"pointer-lock-error",{"has-pointer-lock":!!document.pointerLockElement})})}});
