function k(b,a,c,d){b.v.zb(b.bb,a,c,d,void 0)}function l(b,a,c,d){b.v.ia?k(b,a,c,d):b.v.se()._OnMessageFromDOM({type:"event",component:b.bb,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.C(b.bb,a,c)}function aa(b,a){for(const [c,d]of a)n(b,c,d)}function r(b){b.Kb||(b.v.le(b.Kd),b.Kb=!0)}window.xb=class{constructor(b,a){this.v=b;this.bb=a;this.Kb=!1;this.Kd=()=>this.xa()}Uc(){}xa(){}};function ba(b){-1!==b.Ta&&(self.clearTimeout(b.Ta),b.Ta=-1)}
window.ie=class{constructor(b){this.Ac=b;this.He=5;this.Ta=-1;this.Mb=-Infinity;this.Ld=()=>{this.Ta=-1;this.Mb=Date.now();this.hb=!0;this.Ac();this.hb=!1};this.md=this.hb=!1}j(){ba(this);this.Ld=this.Ac=null}};"use strict";function ca(b,a){n(b,"get-element",c=>{const d=b.ga.get(c.elementId);return a(d,c)})}
window.af=class extends self.xb{constructor(b,a){super(b,a);this.ga=new Map;this.zc=!0;aa(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=this.ga.get(c);this.zc&&d.parentElement.removeChild(d);this.ga.delete(c)}],["set-visible",c=>{this.zc&&(this.ga.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.zc){var d=this.ga.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=
c.height+"px";c=c.fontSize;null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{this.ga.get(c.elementId);throw Error("required override");}],["focus",c=>{const d=this.ga.get(c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{this.ga.get(c.elementId).style[c.prop]=c.val}],["set-attribute",c=>{this.ga.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.ga.get(c.elementId).removeAttribute(c.name)}]]);ca(this,c=>c)}};"use strict";
const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),u=/android/i.test(navigator.userAgent);let ea=0;function v(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Re?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.Ve+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;
function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let w=new Audio;const ja={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;
async function ka(b){b=await la(b);return(new TextDecoder("utf-8")).decode(b)}function la(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const x=[];let z=0;window.RealFile=window.File;const A=[],B=new Map,C=new Map;let ma=0;const na=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");na.push(b)};const oa=new Set(["cordova","playable-ad","instant-games"]);
let pa=!1;
window.Bb=class b{constructor(a){this.ia=a.Xe;this.ta=null;this.aa="";this.ac=a.Ue;this.vb={};this.Ma=this.ub=null;this.Ib=[];this.H=this.Ra=null;this.Ic=!1;this.pd=0;this.jb=null;this.Qa=-1;this.Me=()=>this.ze();this.Pa=[];this.D=a.Md;this.Lb="file"===location.protocol.substr(0,4);!this.ia||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.ia=!1);if("playable-ad"===this.D||"instant-games"===this.D)this.ia=!1;if("cordova"===this.D&&this.ia)if(u){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.ia=!1)}else this.ia=!1;this.Pb=this.ma=null;"html5"!==this.D||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.ve(c));this.C("runtime","create-job-worker",()=>this.we());"cordova"===this.D?document.addEventListener("deviceready",()=>this.dd(a)):this.dd(a)}j(){this.qc();
this.ta&&(this.ta=this.ta.onmessage=null);this.ub&&(this.ub.terminate(),this.ub=null);this.Ma&&(this.Ma.j(),this.Ma=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}fe(){return da&&"cordova"===this.D}mc(){const a=navigator.userAgent;return da&&oa.has(this.D)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}de(){return u}Zc(){return u&&oa.has(this.D)}async dd(a){"macos-wkwebview"===this.D&&this.Ee();if("playable-ad"===this.D){this.ma=self.c3_base64files;this.Pb={};await this.oe();
for(let d=0,e=a.Ua.length;d<e;++d){var c=a.Ua[d].toLowerCase();this.Pb.hasOwnProperty(c)?a.Ua[d]={Re:!0,Ve:this.Pb[c]}:this.ma.hasOwnProperty(c)&&(a.Ua[d]=URL.createObjectURL(this.ma[c]))}}a.Te?this.aa=a.Te:(c=location.origin,this.aa=("null"===c?"file:///":c)+location.pathname,c=this.aa.lastIndexOf("/"),-1!==c&&(this.aa=this.aa.substr(0,c+1)));a.Ze&&(this.vb=a.Ze);c=new MessageChannel;this.ta=c.port1;this.ta.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>
this.ye(d));this.jb=new self.ge(this);await qa(this.jb);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ia?await this.ue(a,c.port2):await this.te(a,c.port2)}sc(a){a=this.vb.hasOwnProperty(a)?this.vb[a]:a.endsWith("/workermain.js")&&this.vb.hasOwnProperty("workermain.js")?this.vb["workermain.js"]:
"playable-ad"===this.D&&this.ma.hasOwnProperty(a.toLowerCase())?this.ma[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async hc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.D&&this.Lb)return a=await this.wb(d.Qe?a:this.ac+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}ra(){return Math.max(window.innerWidth,1)}ja(){return Math.max(window.innerHeight,1)}cd(a){var c=this.aa,d=location.href,e=this.ra(),f=this.ja(),g=window.devicePixelRatio,h=b.Ya(),m=a.ef,p=window.cr_previewImageBlobs||this.ma,q=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,y=window.cf||"";a=a.Md;var W=(new URLSearchParams(self.location.search)).has("debug"),D=this.jb;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:t,swClientId:y,exportType:a,isDebug:W,ife:!!self.df,jobScheduler:{inputPort:D.Hc,outputPort:D.Oc,maxNumWorkers:D.Je},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.ac+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.ac+"opus.wasm.wasm",isFileProtocol:this.Lb,isiOSCordova:this.fe(),isiOSWebView:this.mc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async ue(a,
c){var d=this.sc(a.Ye);this.ub=await this.hc(d,this.aa,{type:"module",name:"Runtime",Qe:!0});this.H=document.createElement("canvas");this.H.style.display="none";d=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.Tc||[],f=a.Ua;e=await Promise.all(e.map(g=>this.Ha(g)));f=await Promise.all(f.map(g=>this.Ha(g)));if("cordova"===this.D)for(let g=0,h=a.dc.length;g<h;++g){const m=a.dc[g],p=
m[0];if(p===a.Rc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))m[1]=await this.Ha(p)}this.ub.postMessage(Object.assign(this.cd(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,workerDependencyScripts:e,engineScripts:f,projectScripts:a.dc,mainProjectScript:a.Rc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...ra(this.jb)]);this.Ib=A.map(g=>new g(this));this.bd();self.c3_callFunction=(g,h)=>{var m=this.Ra;return m.v.ad(m.bb,"js-invoke-function",{name:g,params:h},
void 0,void 0)};"preview"===this.D&&(self.goToLastErrorScript=()=>this.zb("runtime","go-to-last-error-script"))}async te(a,c){this.H=document.createElement("canvas");this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Ib=A.map(g=>new g(this));this.bd();var d=a.Ua.map(g=>"string"===typeof g?(new URL(g,this.aa)).toString():g);Array.isArray(a.Tc)&&d.unshift(...a.Tc);d=await Promise.all(d.map(g=>this.Ha(g)));
await Promise.all(d.map(g=>v(g)));d=self.C3_ProjectScriptsStatus;const e=a.Rc,f=a.dc;for(let [g,h]of f)if(h||(h=g),g===e)try{h=await this.Ha(h),await v(h),"preview"!==this.D||d[g]||this.fd(g,"main script did not run to completion")}catch(m){this.fd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ha(h),await v(h);"preview"===this.D&&"object"!==typeof self.$e.bf?(this.Eb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.cd(a),{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:na}),this.ed(),this.Ma=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.Ma,a))}fd(a,c){this.Eb();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}ed(){this.Eb()}Eb(){const a=
window.Oe;a&&(a.parentElement.removeChild(a),window.Oe=null)}async we(){const a=await sa(this.jb);return{outputPort:a,transferables:[a]}}se(){if(this.ia)throw Error("not available in worker mode");return this.Ma}zb(a,c,d,e,f){this.ta.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}ad(a,c,d,e,f){const g=ma++,h=new Promise((m,p)=>{C.set(g,{resolve:m,reject:p})});this.ta.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.xe(a);if("result"===c)this.Ae(a);else if("runtime-ready"===c)this.Be();else if("alert-error"===c)this.Eb(),alert(a.message);else if("creating-runtime"===c)this.ed();else throw Error(`unknown message '${c}'`);}xe(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=B.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Db(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Db(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Db(f,!1,""+h)}):this.Db(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Db(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.ta.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}Ae(a){const c=a.responseId,d=a.isOk;a=a.result;const e=C.get(c);d?e.resolve(a):e.reject(a);C.delete(c)}C(a,
c,d){let e=B.get(a);e||(e=new Map,B.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static ec(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}bd(){for(const a of this.Ib)if("runtime"===a.bb){this.Ra=a;return}throw Error("cannot find runtime DOM handler");}ye(a){this.zb("debugger","message",a)}Be(){for(const a of this.Ib)a.Uc()}static Ya(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
pa)}static gd(a){pa=!!a}le(a){this.Pa.push(a);this.xc()}De(a){a=this.Pa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Pa.splice(a,1);this.Pa.length||this.qc()}xc(){-1===this.Qa&&this.Pa.length&&(this.Qa=requestAnimationFrame(this.Me))}qc(){-1!==this.Qa&&(cancelAnimationFrame(this.Qa),this.Qa=-1)}ze(){this.Qa=-1;for(const a of this.Pa)a();this.xc()}ya(a){this.Ra.ya(a)}Ga(a){this.Ra.Ga(a)}wc(){this.Ra.wc()}Cb(a){this.Ra.Cb(a)}ee(){return!!ja["audio/webm; codecs=opus"]}async Fe(a){a=await this.ad("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}je(a){this.Ic=!0;this.pd=a}ce(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}$c(a){return!this.ce(a)}async Ha(a){return"cordova"===this.D&&(a.startsWith("file:")||this.Lb&&this.$c(a))?(a.startsWith(this.aa)&&(a=a.substr(this.aa.length)),a=await this.wb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async ve(a){const c=a.filename;switch(a.as){case "text":return await this.be(c);
case "buffer":return await this.wb(c);default:throw Error("unsupported type");}}Xc(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async be(a){a=await this.Xc(a);return await ka(a)}rc(){if(x.length&&!(8<=z)){z++;var a=x.shift();this.pe(a.filename,a.We,a.Pe)}}wb(a){return new Promise((c,d)=>{x.push({filename:a,We:e=>{z--;this.rc();c(e)},Pe:e=>{z--;this.rc();d(e)}});this.rc()})}async pe(a,
c,d){try{const e=await this.Xc(a),f=await la(e);c(f)}catch(e){d(e)}}Ee(){var a={type:"ready"};if("windows-webview2"===this.D)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.D)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async oe(){const a=[];for(const [c,d]of Object.entries(this.ma))a.push(this.ne(c,d));await Promise.all(a)}async ne(a,c){if("object"===typeof c)this.ma[a]=new Blob([c.str],
{type:c.type}),this.Pb[a]=c.str;else{let d=await this.re(c);d||(d=this.qe(c));this.ma[a]=d}}async re(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}qe(a){a=this.Ce(a);return this.me(a.data,a.Se)}Ce(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");
var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Se:a,data:d}}me(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const E=self.Bb;
function ta(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),F={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},G={dispatchRuntimeEvent:!0};
function wa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function xa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function H(b){b=URL.createObjectURL(b);try{return await xa(b)}finally{URL.revokeObjectURL(b)}}
function ya(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function za(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await H(b);var d=await ya(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await H(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await H(b)}
function I(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Aa=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);function J(b){Ba.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ca(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await H(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await za(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let K=!1;document.addEventListener("pause",()=>K=!0);document.addEventListener("resume",()=>K=!1);async function Da(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Ea(b){return await self.C3_GetSvgImageSize(b.blob)}
function Fa(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ga(b){self.setTimeout(()=>{b.od=!0},1E3);"cordova"===b.v.D?(document.addEventListener("pause",()=>Ia(b,!0)),document.addEventListener("resume",()=>Ia(b,!1))):document.addEventListener("visibilitychange",()=>Ia(b,document.hidden));return{isSuspended:!(!document.hidden&&!K)}}
function Ja(b){b.jd||(b.jd=!0,window.addEventListener("deviceorientation",a=>{b.Y||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},F)}),window.addEventListener("deviceorientationabsolute",a=>{b.Y||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},F)}))}
function Ka(b){b.hd||(b.hd=!0,window.addEventListener("devicemotion",a=>{if(!b.Y){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},F)}}))}async function La(b){await wa(b.url)}
function Ma(b,a){b.qd=a.message;-1===b.Dc&&(b.Dc=setTimeout(()=>{b.Dc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.qd)},250))}function L(b){if(!b.Y){var a=E.Ya();a&&"any"!==b.Pc&&Na(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.ra(),innerHeight:b.ja()})}}function Oa(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:E.Ya(),innerWidth:b.ra(),innerHeight:b.ja()})}
function Ia(b,a){a?b.v.qc():b.v.xc();k(b,"visibilitychange",{hidden:a})}function Pa(b,a,c){"Backspace"===c.key&&J(c);if(!b.Y){var d=ua.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},F)}}
function Qa(b,a,c,d){b.Y||ta(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY+b.Z,pageX:c.pageX,pageY:c.pageY+b.Z,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Ra(b){window!==window.top&&window.focus();Sa(b.target)&&document.activeElement&&!Sa(document.activeElement)&&document.activeElement.blur()}
function M(b,a,c){if(!b.Y){if(b.rb&&"pointermove"!==a){var d=b.rb;d.hb||(ba(d),d.Mb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.ob);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Z,pageX:c.pageX,pageY:c.pageY+b.Z,movementX:(c.movementX||0)+b.Wb,movementY:(c.movementY||0)+b.Xb,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||
0,twist:c.twist||0,timeStamp:c.timeStamp},F);b.Wb=0;b.Xb=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Qa(b,d,c,va),b.ob=c.buttons)}}
function Ta(b,a,c){if(!b.Y&&!ta(c)){var d=b.ob;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY+b.Z,pageX:c.pageX,pageY:c.pageY+b.Z,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},F);b.ob=c.buttons;Qa(b,c.type,c,va)}}
function N(b,a,c){if(!b.Y)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY+b.Z,pageX:f.pageX,pageY:f.pageY+b.Z,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},
F)}}function Ua(b,a,c){document.body.style.transform="";b.Z=0;if(0<c){var d=document.activeElement;d&&(d=d.getBoundingClientRect(),a=(d.top+d.bottom)/2-(a-c)/2,a>c&&(a=c),0>a&&(a=0),0<a&&(document.body.style.transform=`translateY(${-a}px)`,b.Z=a))}}function Wa(b,a,c,d){const e=b.ra(),f=b.ja();b.Sa=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.Ya()}):10>d&&Xa(b,e,f,d+1)}
function Xa(b,a,c,d){-1!==b.Sa&&clearTimeout(b.Sa);b.Sa=setTimeout(()=>Wa(b,a,c,d),48)}
function Na(b){b=b.Pc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Sa(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
E.ec(class extends self.xb{constructor(b){super(b,"runtime");this.vd=!0;this.Sa=-1;this.Pc="any";this.hd=this.jd=!1;this.Ba=null;this.Y=!1;this.qd="";this.Dc=-1;this.La=this.rb=null;this.Xb=this.Wb=0;this.od=!1;this.Ad=b.ra();this.Nb=b.ja();this.Z=this.tb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Ic||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.vd&&(e.style.display="",this.vd=!1))});b.C("runtime",
"invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","raster-svg-image",d=>Da(d));b.C("runtime","get-svg-image-size",d=>Ea(d));b.C("runtime","set-target-orientation",d=>{this.Pc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Fa(d));b.C("runtime","go-to-script",d=>
Fa(d));b.C("runtime","before-start-ticking",()=>Ga(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.Ba||(this.Ba=document.createElement("div"),this.Ba.id="inspectOutline",document.body.appendChild(this.Ba));var e=this.Ba;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.Ba&&(this.Ba.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ja(this));b.C("runtime","enable-device-motion",
()=>Ka(this));b.C("runtime","add-stylesheet",d=>La(d));b.C("runtime","alert",d=>{alert(d.message)});b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.Y=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.H.style.display="";this.v.je(d.duration)});b.C("runtime",
"export-to-video-progress",d=>Ma(this,d));b.C("runtime","exported-to-video",d=>{window.Ne({type:"exported-video",blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Ne({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time,gif:d.gif})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||I(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",J);window.addEventListener("gesturehold",
J);c.addEventListener("selectstart",J);c.addEventListener("gesturehold",J);window.addEventListener("touchstart",J,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",J,{passive:!1}),c.addEventListener("pointerdown",J)):c.addEventListener("touchstart",J);this.ob=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",
()=>{a:{if(!this.Y){var d=this.ra();var e=this.ja();if(this.v.Zc()){if(this.od){if(this.Ad===d&&e<this.Nb){this.tb=this.Nb-e;Ua(this,this.Nb,this.tb);d=void 0;break a}0<this.tb&&(this.tb=0,Ua(this,e,this.tb))}this.Ad=d;this.Nb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.Ya()});this.v.mc()&&(-1!==this.Sa&&clearTimeout(this.Sa),Wa(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>L(this));window.addEventListener("webkitfullscreenchange",
()=>L(this));window.addEventListener("mozfullscreenchange",()=>L(this));window.addEventListener("fullscreenerror",d=>Oa(this,d));window.addEventListener("webkitfullscreenerror",d=>Oa(this,d));window.addEventListener("mozfullscreenerror",d=>Oa(this,d));if(b.mc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;
if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):I(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(E.gd(!0),L(this)):"exited-fullscreen"===d?(E.gd(!1),L(this)):console.warn("Unknown wrapper message: ",d)};this.Na=new Set;this.Rb=new WeakSet;this.sa=!1}Uc(){window.addEventListener("focus",()=>{k(this,"window-focus",
null,G)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},G);this.ob=0});window.addEventListener("focusin",a=>{a=a.target;(Aa.has(a.tagName.toLowerCase())||I(a))&&k(this,"keyboard-blur",null,G)});window.addEventListener("keydown",a=>Pa(this,"keydown",a));window.addEventListener("keyup",a=>Pa(this,"keyup",a));window.addEventListener("dblclick",a=>Qa(this,"dblclick",a,F));window.addEventListener("wheel",
a=>{this.Y||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY+this.Z,pageX:a.pageX,pageY:a.pageY+this.Z,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},F)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Ra(a);M(this,"pointerdown",a)}),this.v.ia&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.rb=new self.ie(()=>{M(this,"pointermove",this.La);this.La=null}),this.rb.md=!0,window.addEventListener("pointerrawupdate",
a=>{this.La&&(this.Wb+=this.La.movementX||0,this.Xb+=this.La.movementY||0);this.La=a;a=this.rb;if(-1===a.Ta){var c=Date.now(),d=c-a.Mb,e=a.He;d>=e&&a.md?(a.Mb=c,a.hb=!0,a.Ac(),a.hb=!1):a.Ta=self.setTimeout(a.Ld,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>M(this,"pointermove",a)),window.addEventListener("pointerup",a=>M(this,"pointerup",a)),window.addEventListener("pointercancel",a=>M(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Ra(a);Ta(this,"pointerdown",a)}),
window.addEventListener("mousemove",a=>Ta(this,"pointermove",a)),window.addEventListener("mouseup",a=>Ta(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Ra(a);N(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>N(this,"pointermove",a)),window.addEventListener("touchend",a=>N(this,"pointerup",a)),window.addEventListener("touchcancel",a=>N(this,"pointercancel",a)));const b=()=>this.wc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",
b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.de()&&!this.v.Zc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ua(this,this.ja(),navigator.virtualKeyboard.boundingRect.height)}))}ra(){return this.v.ra()}ja(){return this.v.ja()}wc(){var b=[...this.Na];this.Na.clear();if(!this.sa)for(const a of b)(b=a.play())&&b.catch(()=>{this.Rb.has(a)||this.Na.add(a)})}ya(b){if("function"!==
typeof b.play)throw Error("missing play function");this.Rb.delete(b);let a;try{a=b.play()}catch(c){this.Na.add(b);return}a&&a.catch(()=>{this.Rb.has(b)||this.Na.add(b)})}Ga(b){this.Na.delete(b);this.Rb.add(b)}Cb(b){this.sa=!!b}});"use strict";
async function qa(b){if(b.Ge)throw Error("already initialised");b.Ge=!0;var a=b.$b.sc("dispatchworker.js");b.Cc=await b.$b.hc(a,b.ab,{name:"DispatchWorker"});a=new MessageChannel;b.Hc=a.port1;b.Cc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Oc=await sa(b)}function ra(b){return[b.Hc,b.Oc]}
async function sa(b){const a=b.xd.length;var c=b.$b.sc("jobworker.js");c=await b.$b.hc(c,b.ab,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Cc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.xd.push(c);return e.port1}
self.ge=class{constructor(b){this.$b=b;this.ab=b.aa;this.ab="preview"===b.D?this.ab+"workers/":this.ab+b.ac;this.Je=Math.min(navigator.hardwareConcurrency||2,16);this.Cc=null;this.xd=[];this.Oc=this.Hc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Bb({Xe:!0,Ye:"workermain.js",Ua:["scripts/c3runtime.js"],dc:[],Rc:"",Ue:"scripts/",Tc:[],Md:"html5"}));"use strict";let Ya=!1;
async function Za(b){var a=$a(b.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:b.duration,startDelay:0,weakMagnitude:b.weakMag,strongMagnitude:b.strongMag})}catch(c){console.warn("[Gamepad] Failed to vibrate gamepad: ",c)}}function O(){try{return Array.from(navigator.getGamepads()).filter(b=>b&&b.connected)}catch(b){return Ya||(console.warn("[Construct] Failed to access gamepads: ",b),Ya=!0),[]}}
function $a(b){for(const a of O())if(a.index===b)return a;return null}
self.Bb.ec(class extends self.xb{constructor(b){super(b,"gamepad");this.wd=!!navigator.getGamepads;this.Kc=!1;n(this,"is-supported",()=>this.wd);n(this,"ready",()=>{this.Kc=!0;for(const a of O())k(this,"gamepad-connected",{index:a.index,id:a.id});this.wd&&r(this)});n(this,"vibrate",a=>Za(a));n(this,"reset-vibrate",a=>{(a=$a(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.Kc&&(a=a.gamepad,k(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.Kc&&k(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of O()){const c=a.vibrationActuator;c&&c.reset&&c.reset()}})}xa(){var b=O();b.length&&(b=b.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(c=>({pressed:c.pressed,value:c.value})),axes:a.axes})),k(this,"input-update",b))}});"use strict";const ab=180/Math.PI;
async function bb(b,a){a.isiOSCordova&&(b.Ub=!0);b.Qc=a.timeScaleMode;b.Dd=["equalpower","HRTF","soundfield"][a.panningModel];b.nd=["linear","inverse","exponential"][a.distanceModel];b.Ed=a.refDistance;b.Cd=a.maxDistance;b.Gd=a.rolloffFactor;if(b.v.Ic)b.Ub=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.pd)});else{var c={latencyHint:a.latencyHint};b.Jd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");cb(b);b.g.onstatechange=()=>{"running"!==b.g.state&&cb(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ja=b.g.createGain();b.Ja.connect(b.g.destination);c=a.listenerPos;b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",
d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state,outputLatency:b.g.outputLatency||0}}
async function db(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.yd=g;eb(b,g);try{b.la=await fb(b,c,d,e,g,f);if(q){Q(b.la,!0);var y=b.la,W=q.innerAngle,D=q.outerAngle,rb=q.outerGain;if(y.ib){gb(y,q.x,q.y,q.angle);var Ha=self.Va.ke;y.F.coneInnerAngle=Ha(W);y.F.coneOuterAngle=
Ha(D);y.F.coneOuterGain=rb}q.hasOwnProperty("uid")&&(b.la.ka=q.uid)}else Q(b.la,!1);b.la.Play(h,m,p,t)}catch(sb){console.error("[Construct] Audio: error starting playback: ",sb);return}finally{c=b.qb.get(g);if(!c)throw Error("expected pending tag");c.Sc--;0===c.Sc&&(c.resolve(),b.qb.delete(g))}r(b)}
async function hb(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await ib(b,c);for(const q of R(b,c)){c=q;var f=d,g=e,h=a;if(!c.Ka){var m=c.N.gain;m.cancelScheduledValues(0);var p=c.s.g.currentTime;g=p+g;m.setValueAtTime(m.value,p);m.linearRampToValueAtTime(f,g);c.Ea=f;c.fb=g;c.Id=h}}S(b)}async function jb(b,a){const c=a.tag;a=a.rate;await ib(b,c);for(const d of R(b,c))b=d,b.ha!==a&&(b.ha=a,b.za())}
async function kb(b,a){const c=a.tag;a=a.pos;await ib(b,c);for(const d of R(b,c))d.nc(a)}async function lb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await fb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function mb(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ea.indexOf(a),-1!==a&&b.ea.splice(a,1)}
async function nb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Sd(b,...e);else if("delay"===c)e=new self.Qd(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Pd(b,c.da,...e);var f=a.bufferType;c.kd=a.bufferOriginalUrl;c.ld=f}else if("flanger"===c)e=new self.Td(b,...e);else if("phaser"===c)e=new self.Vd(b,...e);else if("gain"===c)e=
new self.Ud(b,...e);else if("tremolo"===c)e=new self.Xd(b,...e);else if("ringmod"===c)e=new self.Wd(b,...e);else if("distortion"===c)e=new self.Rd(b,...e);else if("compressor"===c)e=new self.Od(b,...e);else if("analyser"===c)e=new self.Nd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.fa.get(d);e||(e=[],b.fa.set(d,e));a.ud=e.length;a.ba=d;e.push(a);ob(b,d);pb(b)}
async function qb(b,a){const c=a.saveLoadMode;if(3!==c)for(var d of b.L)d.wa()&&1===c||(d.wa()||2!==c)&&d.qa();for(const e of b.fa.values())for(const f of e)f.j();b.fa.clear();b.bc=a.timeScale;b.Ec=a.gameTime;d=a.listenerPos;b.g.listener.setPosition(d[0],d[1],d[2]);b.sa=a.isSilent;b.v.Cb(b.sa);b.Qb=a.masterVolume;b.Ja.gain.value=b.Qb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>nb(b,f))));await Promise.all(d);await Promise.all(a.playing.map(e=>tb(b,e,c)));S(b)}
async function ub(b,a){try{const c=b.g.suspend(a.time);b.td?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.zb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>vb(d)),b.td=!0);await c}catch(c){vb(c)}}
function cb(b){b.Jb||(b.Gc=!1,window.addEventListener("pointerup",b.ua,!0),window.addEventListener("touchend",b.ua,!0),window.addEventListener("click",b.ua,!0),window.addEventListener("keydown",b.ua,!0),b.Jb=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ea)if(g.Xa()===c)return await wb(g),g;if(f)return null;if(e&&(b.Ub||b.sd)){f=0;for(let h=0,m=b.ea.length;h<m;++h)g=b.ea[h],b.ea[f]=g,g.wa()?g.j():++f;b.ea.length=f}f="audio/webm; codecs=opus"===d&&!b.Jd;e&&f&&(b.sd=!0);c=!e||b.Ub||f?new self.$d(b,a,c,d,e,f):new self.Yd(b,a,c,d,e);b.ea.push(c);await wb(c);b.Bd.has(a)||(k(b,"buffer-metadata",{originalUrl:a,duration:c.ca()}),b.Bd.add(a));return c}
function yb(b,a){return(a=b.fa.get(a.toLowerCase()))?a[0].R():b.va()}function ob(b,a){let c=b.va();var d=b.fa.get(a);if(d&&d.length){c=d[0].R();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.va()):e.U(d[f+1].R())}}for(const f of R(b,a))d=c,e=f.F||f.N,e.disconnect(),e.connect(d);b.Ca&&b.Mc===a&&(b.Ca.disconnect(),b.Ca.connect(c))}function*R(b,a){if(a)for(const c of b.L)b=c.ba,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.la&&!b.la.S()&&(yield b.la)}
function zb(b,a,c){return c?b.v.Fe(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function Ab(b,a){let c=0;for(let d=0,e=b.L.length;d<e;++d){const f=b.L[d];b.L[c]=f;f.M===a?f.j():++c}b.L.length=c}async function fb(b,a,c,d,e,f){for(const g of b.L)if(g.Xa()===c&&(g.fc()||f))return g.ba=e,g;a=await P(b,a,c,d,f);e="html5"===a.yc?new self.Zd(a.s,a,e):new self.ae(a.s,a,e);b.L.push(e);return e}
function eb(b,a){let c=b.qb.get(a);if(!c){let d=null;c={Sc:0,promise:new Promise(e=>d=e),resolve:d};b.qb.set(a,c)}c.Sc++}function ib(b,a){a||(a=b.yd);return(b=b.qb.get(a))?b.promise:Promise.resolve()}function S(b){if(0<b.Ia.size)r(b);else for(const a of b.L)if(!a.G&&!a.S()){r(b);break}}function Cb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function pb(b){b.Jc||(b.Jc=!0,Promise.resolve().then(()=>Db(b)))}
function Db(b){const a={};for(const [c,d]of b.fa)a[c]=d.map(e=>e.Wa());k(b,"fxstate",{fxstate:a});b.Jc=!1}
async function tb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await fb(b,d,e,f,h,g)}catch(t){console.error("[Construct] Audio: error loading audio state: ",t);return}b=c;(d=a.pan)?(Q(b,!0),e=b.F,f=d.pos,b.oa[0]=f[0],b.oa[1]=f[1],b.oa[2]=f[2],f=d.orient,b.na[0]=f[0],b.na[1]=f[1],b.na[2]=f[2],e.setPosition(...b.oa),e.setOrientation(...b.na),e.coneInnerAngle=d.cia,e.coneOuterAngle=
d.coa,e.coneOuterGain=d.cog,b.ka=d.uid):Q(b,!1);c.Play(m,p,q,0);a.isPlaying||c.Za();c.uc(a)}}}function vb(b){console.error("[Audio] Offline rendering error: ",b)}
self.Va=class extends self.xb{constructor(b){super(b,"audio");this.Ja=this.g=null;this.Jb=this.Gc=!1;this.ua=()=>{if(!this.Gc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Jb&&(this.Gc=!0,window.removeEventListener("pointerup",this.ua,!0),window.removeEventListener("touchend",this.ua,!0),window.removeEventListener("click",this.ua,!0),window.removeEventListener("keydown",
this.ua,!0),this.Jb=!1)}};this.ea=[];this.L=[];this.la=null;this.yd="";this.Bd=new Set;this.zd=-1;this.qb=new Map;this.Qb=1;this.sa=!1;this.Qc=0;this.bc=1;this.Ec=0;this.Dd="HRTF";this.nd="inverse";this.Ed=600;this.Cd=1E4;this.Gd=1;this.sd=this.Ub=!1;this.Jd=this.v.ee();this.fa=new Map;this.Ia=new Set;this.td=this.Jc=!1;this.Mc="";this.Ca=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Ca&&this.Ca.disconnect();this.Mc=c.toLowerCase();this.Ca=this.g.createMediaStreamSource(a);this.Ca.connect(yb(this,
this.Mc))};this.Hb=null;self.C3Audio_GetOutputStream=()=>{this.Hb||(this.Hb=this.g.createMediaStreamDestination(),this.Ja.connect(this.Hb));return this.Hb.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>bb(this,a)],["play",a=>db(this,a)],["stop",a=>{a=a.tag;for(const c of R(this,a))c.qa()}],["stop-all",()=>{for(const a of this.L)a.qa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of R(this,c))a?d.Za():d.Ab();S(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;
for(const d of R(this,c))T(d,a)}],["fade-volume",a=>hb(this,a)],["set-master-volume",a=>{this.Qb=a.vol;this.Ja.gain.value=this.Qb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of R(this,c))Eb(d,a)}],["set-silent",a=>{this.sa=a.isSilent;this.v.Cb(this.sa);for(const c of this.L)c.Fb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of R(this,c))d.oc(a)}],["set-playback-rate",a=>jb(this,a)],["seek",a=>kb(this,a)],["preload",a=>lb(this,a)],["unload",a=>mb(this,a)],["unload-all",
()=>{for(const a of this.ea)a.j();this.ea.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.L)c.pc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>nb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.fa.get(a.tag);!a||0>c||c>=a.length||(a[c].$(d,e,f,g),pb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.fa.get(a);if(c&&c.length){for(const d of c)d.j();this.fa.delete(a);ob(this,
a)}}],["tick",a=>{this.bc=a.timeScale;this.Ec=a.gameTime;this.zd=a.tickCount;if(0!==this.Qc)for(var c of this.L)c.za();(c=a.listenerPos)&&this.g.listener.setPosition(c[0],c[1],c[2]);for(const d of a.instPans){a=d.uid;for(const e of this.L)e.ka===a&&gb(e,d.x,d.y,d.angle)}}],["load-state",a=>qb(this,a)],["offline-render-audio",a=>ub(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}X(){return this.g}va(){return this.Ja}yb(){return this.sa}ya(b){this.v.ya(b)}Ga(b){this.v.Ga(b)}xa(){for(var b of this.Ia)b.xa();
b=this.g.currentTime;for(var a of this.L)a.xa(b);a=this.L.filter(c=>!c.G&&!c.S()).map(c=>c.Wa());k(this,"state",{tickCount:this.zd,outputLatency:this.g.outputLatency||0,audioInstances:a,analysers:[...this.Ia].map(c=>({tag:c.ba,index:c.ud,peak:c.Oa,rms:c.Fd,binCount:c.m.frequencyBinCount,freqBins:c.rd}))});0===a.length&&0===this.Ia.size&&this.Kb&&(this.v.De(this.Kd),this.Kb=!1)}static ke(b){return b*ab}static Yc(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static he(b){return Math.log(Math.max(Math.min(b,
1),0))/Math.log(10)*20}};self.Bb.ec(self.Va);"use strict";function wb(b){b.Ob||(b.Ob=b.tc());return b.Ob}self.Vc=class{constructor(b,a,c,d,e){this.s=b;this.Le=a;this.Da=c;this.T=d;this.Ie=e;this.yc="";this.Ob=null}j(){this.Ob=this.s=null}tc(){}X(){return this.s.X()}jc(){return this.Le}Xa(){return this.Da}ic(){return this.T}wa(){return this.Ie}ca(){}};"use strict";
self.Yd=class extends self.Vc{constructor(b,a,c,d,e){super(b,a,c,d,e);this.yc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.kb=this.lb=null;this.K.addEventListener("canplaythrough",()=>!0);this.pb=this.X().createGain();this.nb=null;this.K.addEventListener("canplay",()=>{this.lb&&(this.lb(),this.kb=this.lb=null);!this.nb&&this.K&&(this.nb=this.X().createMediaElementSource(this.K),this.nb.connect(this.pb))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Da}' error: `,f);this.kb&&(this.kb(f),this.kb=this.lb=null)})}j(){Ab(this.s,this);this.pb.disconnect();this.pb=null;this.nb.disconnect();this.nb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.j()}tc(){return new Promise((b,a)=>{this.lb=b;this.kb=a;this.K.src=this.Da})}P(){return this.K}ca(){return this.K.duration}};"use strict";
async function Fb(b){if(b.Aa)return b.Aa;var a=b.s.v;if("cordova"===a.D&&a.$c(b.Da)&&a.Lb)b.Aa=await a.wb(b.Da);else{a=await fetch(b.Da);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.Aa=await a.arrayBuffer()}}async function Gb(b){if(b.da)return b.da;b.da=await zb(b.s,b.Aa,b.Ke);b.Aa=null}
self.$d=class extends self.Vc{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.yc="webaudio";this.da=this.Aa=null;this.Ke=!!f}j(){Ab(this.s,this);this.da=this.Aa=null;super.j()}async tc(){try{await Fb(this),await Gb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Da}': `,b)}}ca(){return this.da?this.da.duration:0}};"use strict";let Hb=0;
function Q(b,a){a=!!a;b.ib!==a&&(b.ib=a,b.ib?(b.F||(b.F=b.X().createPanner(),b.F.panningModel=b.s.Dd,b.F.distanceModel=b.s.nd,b.F.refDistance=b.s.Ed,b.F.maxDistance=b.s.Cd,b.F.rolloffFactor=b.s.Gd),b.N.disconnect(),b.N.connect(b.F),b.F.connect(b.va())):(b.F.disconnect(),b.N.disconnect(),b.N.connect(b.va())))}function T(b,a){b.Ea=a;b.N.gain.cancelScheduledValues(0);b.fb=-1;b.N.gain.value=b.kc()}function Eb(b,a){a=!!a;b.Ka!==a&&(b.Ka=a,b.Fb())}
function gb(b,a,c,d){b.ib&&(b.oa[0]=a,b.oa[1]=c,b.oa[2]=0,b.na[0]=Math.cos(d),b.na[1]=Math.sin(d),b.na[2]=0,b.F.setPosition(...b.oa),b.F.setOrientation(...b.na))}function U(b){return b.Lc?b.s.Ec:performance.now()/1E3}
self.Wc=class{constructor(b,a,c){this.s=b;this.M=a;this.ba=c;this.Gb=Hb++;this.N=this.X().createGain();this.N.connect(this.va());this.F=null;this.ib=!1;this.oa=[0,0,0];this.na=[0,0,0];this.G=!0;this.W=this.pa=this.I=!1;this.Ea=1;this.Ka=!1;this.ha=1;b=this.s.Qc;this.Lc=1===b&&!this.wa()||2===b;this.fb=this.ka=-1;this.Id=!1}j(){this.M=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.N.disconnect();this.N=null}X(){return this.s.X()}va(){return yb(this.s,this.ba)}jc(){return this.M.jc()}Xa(){return this.M.Xa()}ic(){return this.M.ic()}wa(){return this.M.wa()}S(){}fc(){}IsPlaying(){return!this.G&&
!this.I&&!this.S()}Fa(){}ca(){return this.M.ca()}Play(){}qa(){}Za(){}Ab(){}xa(b){-1!==this.fb&&b>=this.fb&&(this.fb=-1,this.Id&&this.qa(),Cb(this.s,"fade-ended",this.ba,this.Gb))}kc(){const b=this.Ea;return isFinite(b)?b:0}yb(){return this.s.yb()}Fb(){}oc(){}za(){}nc(){}pc(){}lc(){}Wa(){var b=this.Gb,a=this.ba,c=this.ca(),d=this.Ea,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.oa,orient:this.na,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ka}}else f=null;return{aiid:b,
tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Fa(),playbackRate:this.ha,uid:this.ka,bufferOriginalUrl:this.jc(),bufferUrl:"",bufferType:this.ic(),isMusic:this.wa(),isLooping:this.W,isMuted:this.Ka,resumePosition:this.lc(),pan:f}}uc(b){var a=b.playbackRate;this.ha!==a&&(this.ha=a,this.za());Eb(this,b.isMuted)}};"use strict";
self.Zd=class extends self.Wc{constructor(b,a,c){super(b,a,c);this.M.pb.connect(this.N);this.M.onended=()=>this.vc()}j(){this.qa();this.M.pb.disconnect();super.j()}P(){return this.M.P()}vc(){this.G=!0;this.ka=-1;Cb(this.s,"ended",this.ba,this.Gb)}S(){return this.P().ended}fc(){return this.G?!0:this.S()}Fa(){let b=this.P().currentTime;this.W||(b=Math.min(b,this.ca()));return b}Play(b,a,c){const d=this.P();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.M.Xa()}' to position '${c}': `,e)}this.s.ya(d);this.I=this.G=!1;this.W=b;this.ha=1}qa(){const b=this.P();b.paused||b.pause();this.s.Ga(b);this.G=!0;this.I=!1;this.ka=-1}Za(){if(!(this.I||this.G||this.S())){var b=this.P();b.paused||b.pause();this.s.Ga(b);this.I=!0}}Ab(){!this.I||this.G||this.S()||(this.s.ya(this.P()),this.I=!1)}Fb(){this.P().muted=this.Ka||this.yb()}oc(b){b=!!b;this.W!==b&&(this.W=
b,this.P().loop=b)}za(){let b=this.ha;this.Lc&&(b*=this.s.bc);try{this.P().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}nc(b){if(!this.G&&!this.S())try{this.P().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}lc(){return this.Fa()}pc(b){b?this.IsPlaying()?(this.P().pause(),this.pa=!0):this.pa=!1:this.pa&&(this.s.ya(this.P()),this.pa=!1)}};"use strict";function V(b){b.o&&b.o.disconnect();b.o=null;b.$a=null}
self.ae=class extends self.Wc{constructor(b,a,c){super(b,a,c);this.o=null;this.Sb=d=>this.vc(d);this.Fc=!0;this.$a=null;this.O=this.Tb=this.Vb=0;this.Nc=1}j(){this.qa();V(this);this.Sb=null;super.j()}vc(b){this.I||this.pa||b.target!==this.$a||(this.G=this.Fc=!0,this.ka=-1,V(this),Cb(this.s,"ended",this.ba,this.Gb))}S(){return!this.G&&this.o&&this.o.loop||this.I?!1:this.Fc}fc(){return!this.o||this.G?!0:this.S()}Fa(){let b;b=this.I?this.O:this.Tb+(U(this)-this.Vb)*this.ha;this.W||(b=Math.min(b,this.ca()));
return b}Play(b,a,c,d){this.Nc=1;T(this,a);V(this);this.o=this.X().createBufferSource();this.o.buffer=this.M.da;this.o.connect(this.N);this.$a=this.o;this.o.onended=this.Sb;this.o.loop=b;this.o.start(d,c);this.I=this.G=this.Fc=!1;this.W=b;this.ha=1;this.Vb=U(this);this.Tb=c}qa(){if(this.o)try{this.o.stop(0)}catch(b){}this.G=!0;this.I=!1;this.ka=-1}Za(){this.I||this.G||this.S()||(this.O=this.Fa(),this.W&&(this.O%=this.ca()),this.I=!0,this.o.stop(0))}Ab(){!this.I||this.G||this.S()||(V(this),this.o=
this.X().createBufferSource(),this.o.buffer=this.M.da,this.o.connect(this.N),this.$a=this.o,this.o.onended=this.Sb,this.o.loop=this.W,T(this,this.Ea),this.za(),this.o.start(0,this.O),this.Vb=U(this),this.Tb=this.O,this.I=!1)}kc(){return super.kc()*this.Nc}Fb(){this.Nc=this.Ka||this.yb()?0:1;T(this,this.Ea)}oc(b){b=!!b;this.W!==b&&(this.W=b,this.o&&(this.o.loop=b))}za(){let b=this.ha;this.Lc&&(b*=this.s.bc);this.o&&(this.o.playbackRate.value=b)}nc(b){this.G||this.S()||(this.I?this.O=b:(this.Za(),this.O=
b,this.Ab()))}lc(){return this.O}pc(b){b?this.IsPlaying()?(this.pa=!0,this.O=this.Fa(),this.W&&(this.O%=this.ca()),this.o.stop(0)):this.pa=!1:this.pa&&(V(this),this.o=this.X().createBufferSource(),this.o.buffer=this.M.da,this.o.connect(this.N),this.$a=this.o,this.o.onended=this.Sb,this.o.loop=this.W,T(this,this.Ea),this.za(),this.o.start(0,this.O),this.Vb=U(this),this.Tb=this.O,this.pa=!1)}uc(b){super.uc(b);this.O=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.X();this.ud=-1;this.T=this.ba="";this.l=null}j(){this.g=null}R(){}U(){}Wa(){return{type:this.T,tag:this.ba,params:this.l}}}
self.Sd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.l=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.B=this.g.createBiquadFilter();this.B.type=a;this.B.frequency.value=c;this.B.detune.value=d;this.B.Q.value=e;this.B.gain.vlaue=f;this.u.connect(this.B);this.u.connect(this.h);this.B.connect(this.i)}j(){this.u.disconnect();this.B.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.l[1]=a;Y(this,this.B.frequency,a,c,d);break;case 2:this.l[2]=a;Y(this,this.B.detune,a,c,d);break;case 3:this.l[3]=a;Y(this,this.B.Q,a,c,d);break;case 4:this.l[4]=a,Y(this,this.B.gain,a,c,d)}}};
self.Qd=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.l=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.mb=X(this);this.V=this.g.createDelay(a);this.V.delayTime.value=a;this.eb=X(this);this.eb.gain.value=c;this.u.connect(this.mb);this.u.connect(this.h);this.mb.connect(this.i);this.mb.connect(this.V);this.V.connect(this.eb);this.eb.connect(this.mb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.mb.disconnect();
this.V.disconnect();this.eb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){const e=self.Va.Yc;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.l[1]=e(a);Y(this,this.eb.gain,e(a),c,d);break;case 5:this.l[0]=a,Y(this,this.V.delayTime,a,c,d)}}};
self.Pd=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.l=[c,d];this.ld=this.kd="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.cb=this.g.createConvolver();this.cb.normalize=c;this.cb.buffer=a;this.u.connect(this.cb);this.u.connect(this.h);this.cb.connect(this.i)}j(){this.u.disconnect();this.cb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}Wa(){const b=super.Wa();b.bufferOriginalUrl=this.kd;b.bufferUrl="";b.bufferType=this.ld;return b}};
self.Td=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.l=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.gb=X(this);this.gb.gain.value=e;this.V=this.g.createDelay(a+c);this.V.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.J=X(this);this.J.gain.value=c;this.u.connect(this.V);this.u.connect(this.h);this.V.connect(this.i);this.V.connect(this.gb);this.gb.connect(this.V);this.A.connect(this.J);
this.J.connect(this.V.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.V.disconnect();this.A.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();this.gb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.l[1]=a/1E3;Y(this,this.J.gain,a/1E3,
c,d);break;case 7:this.l[2]=a;Y(this,this.A.frequency,a,c,d);break;case 8:this.l[3]=a/100,Y(this,this.gb.gain,a/100,c,d)}}};
self.Vd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.l=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.B=this.g.createBiquadFilter();this.B.type="allpass";this.B.frequency.value=a;this.B.detune.value=c;this.B.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.J=X(this);this.J.gain.value=e;this.u.connect(this.B);this.u.connect(this.h);this.B.connect(this.i);this.A.connect(this.J);this.J.connect(this.B.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.B.disconnect();this.A.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.l[0]=a;Y(this,this.B.frequency,a,c,d);break;case 2:this.l[1]=a;Y(this,this.B.detune,a,c,d);
break;case 3:this.l[2]=a;Y(this,this.B.Q,a,c,d);break;case 6:this.l[3]=a;Y(this,this.J.gain,a,c,d);break;case 7:this.l[4]=a,Y(this,this.A.frequency,a,c,d)}}};self.Ud=class extends Z{constructor(b,a){super(b);this.T="gain";this.l=[a];this.m=X(this);this.m.gain.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(b,a,c,d){const e=self.Va.Yc;switch(b){case 4:this.l[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.Xd=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.l=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.J=X(this);this.J.gain.value=c/2;this.A.connect(this.J);this.J.connect(this.m.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.J.disconnect();this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.J.gain,a/2,c,d);break;case 7:this.l[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.Wd=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.l=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.sb=X(this);this.sb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.sb.gain);this.A.start(0);this.u.connect(this.sb);this.u.connect(this.h);this.sb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.sb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.l[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.Rd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.l=[a,c,d,e,f];this.u=X(this);this.Zb=X(this);this.Yb=X(this);b=d;.01>b&&(b=.01);this.Zb.gain.value=b;this.Yb.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.cc=this.g.createWaveShaper();this.Bc=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Bc[32768+e]=f,this.Bc[32768-
e-1]=-f;this.cc.curve=this.Bc;this.u.connect(this.Zb);this.u.connect(this.h);this.Zb.connect(this.cc);this.cc.connect(this.Yb);this.Yb.connect(this.i)}j(){this.u.disconnect();this.Zb.disconnect();this.cc.disconnect();this.Yb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}$(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Od=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.l=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(){}};
self.Nd=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.l=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.rd=new Float32Array(this.m.frequencyBinCount);this.Hd=new Uint8Array(a);this.Fd=this.Oa=0;b=this.s;b.Ia.add(this);S(b)}j(){this.s.Ia.delete(this);this.m.disconnect();super.j()}xa(){this.m.getFloatFrequencyData(this.rd);this.m.getByteTimeDomainData(this.Hd);const b=this.m.fftSize;let a=this.Oa=0;for(var c=0;c<b;++c){let d=(this.Hd[c]-
128)/128;0>d&&(d=-d);this.Oa<d&&(this.Oa=d);a+=d*d}c=self.Va.he;this.Oa=c(this.Oa);this.Fd=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}$(){}};
